### ISSUE TITLE
When publishing Pubsub message, wait for connected peers

### ISSUE THREAD

**Issue by kevinsimper** [ipfs/js-ipfs#1097]
When you publish a message with pubsub I found that if you are not connected to any peers in the pubsub topic nobody will receive it and it will not wait to send it until you are connected. The callback on `publish` does not tell you anything either that it was not received by anyone.

That is no so intuitive and I know it is because it works by webrtc and therefore can't relay it on something of p2p network where another peer will hold the message and try to deliver it to other peers.

I am not saying it is a bug, but maybe the documentation could be more clear or the code could wait until it has been connected to at least one peer.

See my example with a naive setTimeout to ensure that the other peers receive the message.
https://jsbin.com/rupuvaqose/edit?js,output
 
```
var id = 'ipfs-repo-' + String(Math.random())
const node = new Ipfs({
    repo: id,
    EXPERIMENTAL: {
        pubsub: true
    }
})

node.on('ready', function() {
    // Your node is now ready to use \o/
    console.log('ready')
    // stopping a node

    let topic = 'fruit-of-the-day-kevin'

    let receiveMsg = function(msg) {
        console.log(msg.data.toString())
    }

    node.pubsub.subscribe(topic, receiveMsg)

    setTimeout(() => {
          node.pubsub.publish(topic, new node.types.Buffer('banana' + id))
    }, 2000)
})
```

**Comment by diasdavid** [comment]
The current implementation of PubSub doesn't give you delivery guarantees (reliability) and that is by design of FloodSub, more PubSub implementations to come.

Even correcting to one peer doesn't mean it is the peer that is subscribing, so waiting to connect is not a good rule of thumb. You should write in your code a loop that waits for peers to get connected and if you need reliability, you should check their Ids and then publish the message.

More thoughts and ideas here https://github.com/libp2p/research-pubsub join the convo :)
