### ISSUE TITLE
pubsub/peers topic is optional

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-ipfs#1100]
According to the [docs](https://ipfs.io/docs/api) the `topic` argument is optional in `pubsub/peers`.

[js-ipfs](https://github.com/ipfs/js-ipfs/blob/master/src/http/api/resources/pubsub.js#L102) makes it mandatory.

**Comment by diasdavid** [comment]
Good catch. Open for contribs!

**Comment by haoliangyu** [comment]
I can work on this issue.

Another place that (maybe) needs change is [here](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/pubsub.js#L81) where `topic` is used to filter the peers to return. If the topic is optional, the filtering should be skipped based on the value of topic.

Since the `topic` is optional, do you want to keep the `pubshub.peers(topic, callback)` pattern even the `topic` is nullable, or allow `pubshub.peers(callback)` when `topic` is undefined?

Please advice.

**Comment by richardschneider** [comment]
@haoliangyu Good analysis.  I like having two method signatures
- pubsub.peers (callback)
- pubsub.peers (topic, callback)
