### ISSUE TITLE
Should specify which link didn't exist on ipfs.cat

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs#1145]
https://github.com/ipfs/js-ipfs/blob/master/src/core/components/files.js#L140 should report the same error as js-ipfs-api. 

Example: https://github.com/ipfs/interface-ipfs-core/pull/183#discussion_r156408064

//cc @pgte

**Comment by diasdavid** [comment]
The HTTP API didn't get updated

```
  1) HTTP API
       ## interface-ipfs-core over ipfs-api
         .files
           .cat
             errors on unknown path:
     AssertionError: expected 'Failed to cat file: Error: No such file' to be one of [ Array(2) ]
      at ipfs.files.cat.catch (node_modules/interface-ipfs-core/src/files.js:439:36)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by youngnicks** [comment]
I'm new to ipfs, but am willing to give this a shot. It looks like it is just changing the error message in **src/core/components/files.js** from 'No such file' to `no link named "${fileName}" under ${path}`. Is this correct?

**Comment by youngnicks** [comment]
If the above is true, should the `ipfs/interface-ipfs-core` be updated to remove `No such file` as a valid scenario? The test also fails due to the test looking for the error message thrown in files.cat, however, `Failed to cat file:` is prepended to the error message. I see other tests use `expect(err.message).to.contain` instead of `expect(err.message).to.oneOf`.

```javascript
expect(err.message).to.contain(
  'Error: no link named "does-not-exist" under Qma4hjFTnCasJ8PVp3mZbZK5g2vGDT4LByLJ7m8ciyRFZP'
)
```

**Comment by niinpatel** [comment]
Is this still open? Can I look into this?

**Comment by achingbrain** [comment]
Closing as this issue is very stale.
