### ISSUE TITLE
Websocket down? 

### ISSUE THREAD

**Issue by mitra42** [ipfs/js-ipfs#1237]
Has something changed, or is the websocket sync point moved/down ?

Since yesterday I've been seeing: 
dweb_transport_ipfs_bundled.js:40529 WebSocket connection to 'wss://ws-star.discovery.libp2p.io/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 502

Everything else seems good - e.g. connections to the http gateway at https://ipfs.io are working. 

Version: ipfs 0.27.7
System: OSX (10.13.3 current)
Browsers: Firefox 58.0.2 & Chrome 64.0.3282.167 i.e. both current
My configuration is ... 
```
{
"repo":"/tmp/dweb_ipfsv2700",
"config":{ 
    "Addresses": {
        "Swarm":["/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star"]
}},
"EXPERIMENTAL":{"pubsub":true}
}
```

**Comment by mitra42** [comment]
Thanks Lars - its back. 

Lars - is setting something like this up here at Archive.org part of what David Dias asked you if you could help with ?

**Comment by VictorBjelkholm** [comment]
@lgierth thanks!

@mitra42 to avoid being blocked by experimental services being down in the future, you should run either https://github.com/libp2p/js-libp2p-websocket-star-rendezvous for websockets or https://github.com/libp2p/js-libp2p-webrtc-star for webrtc within your own network.

To get up and running, you should do the following:

- Clone the repository
- Pull down dependencies (`yarn` or `npm install`)
- Run `npm start` for ws-star or `npm run star-signal` for webrtc-star
- Then you can just use the IP + port of star-signal as a multiaddr in your node configuration, instead of the discovery.libp2p.io ones.

**Comment by mitra42** [comment]
@VictorBjelkholm - @diasdavid  had a specific suggestion about what we needed to do at the Archive, and I don't think it was what you are suggesting above - and the sysadmin's couldn't follow what was being requested. He asked @lgierth to help but we haven't heard back.
