### ISSUE TITLE
npm install fails with missing git hook

### ISSUE THREAD

**Issue by dryajov** [ipfs/js-ipfs#1444]
- **Version**: latest master (0.30.0)
- **Platform**: mac osx high sierra (10.13.5 (17F77))
- **Subsystem**: js-ipfs (running node `v9.11.1` and npm `v6.1.0`)

#### Description: `npm install` fails with:
```
> git-validate@2.2.2 install /Users/dryajov/personal/projects/ipfs/ipfs/js-ipfs/node_modules/git-validate
> node bin/install
fs.js:660
  return binding.open(pathModule.toNamespacedPath(path),
                 ^
Error: ENOENT: no such file or directory, open '/Users/dryajov/personal/projects/ipfs/ipfs/js-ipfs/.git/hooks/pre-push'
    at Object.fs.openSync (fs.js:660:18)
    at Object.fs.writeFileSync (fs.js:1319:33)
    at Object.exports.installHooks (/Users/dryajov/personal/projects/ipfs/ipfs/js-ipfs/node_modules/git-validate/lib/utils.js:248:12)
    at Object.<anonymous> (/Users/dryajov/personal/projects/ipfs/ipfs/js-ipfs/node_modules/git-validate/bin/install.js:3:7)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
```

#### Steps to reproduce the error:
- clone this repo and do an `npm i`

**Comment by dryajov** [comment]
This is due to a broken symlink in the `.git/hooks` directory. Removing the symlink (`.git/hooks/pre-push`) and rerunning `npm i` fixes this issue.

**Comment by jacobheun** [comment]
Looking into this it looks like Aegir < 15 was using the `pre-push` modules. In Aegir >= 15 the move was made to use `git-validate`. This issue is that `pre-push` was creating symlinks to itself in the node_modules directory. When `git-validate` does an install it does some inspection on the hook, which now has a dead symlink.

Aside from doing a pre-install removal in aegir, which is probably unnecessary for this, the [removal](https://github.com/ipfs/js-ipfs/issues/1444#issuecomment-405345318) is the quickest fix.

**Comment by vmx** [comment]
Is this OSX specific? It never happened to me (I'm on Linux).

**Comment by vmx** [comment]
Although I prefer having pre-push hooks, I also don't want to see everyone's project broken. I wonder if there's a workaround/better solution.

**Comment by jacobheun** [comment]
Okay, I was able to replicate this consistently with docker, however, it only occurs if the node_modules are removed in between npm installs. Anyone who didn't manually remove the node_modules prior to the install probably won't have the issue.

I don't think we need to do any code changes for this. In theory we could create some backward compatibility support via preinstall scripts, but since we're still in beta releases I think it's okay to just add a quick note about upgrading to 0.30 to the readme in case anyone hits the issue.

Here are the Dockerfile contents for reference:
### Works
```
FROM node:10

RUN git clone https://github.com/ipfs/js-ipfs.git
RUN cd ./js-ipfs && ls -la && \
  git checkout v0.29.3 && \
  npm i && ls -la .git/hooks && \
  git checkout master && \
  npm i && ls -la .git/hooks
```

### Fails
```
FROM node:10

RUN git clone https://github.com/ipfs/js-ipfs.git
RUN cd ./js-ipfs && ls -la && \
  git checkout v0.29.3 && \
  npm i && ls -la .git/hooks && \
  rm .git/hooks/pre-push 2> /dev/null && \
  git checkout master && \
  npm i && ls -la .git/hooks
```

**Comment by PascalPrecht** [comment]
> Anyone who didn't manually remove the node_modules prior to the install probably won't have the issue.

This makes sense. Unfortunately, chances are very high that users do this. Will send a PR to have note int he README.

**Comment by PascalPrecht** [comment]
Turns out this is happening over at `interface-core-ipfs` as well. Created another PR over there accordingly: https://github.com/ipfs/interface-ipfs-core/pull/329

**Comment by vmx** [comment]
The proper solution is to make git-validate not fail. Let's hope this PR gets accepted: https://github.com/nlf/git-validate/pull/67

**Comment by PascalPrecht** [comment]
Nice @vmx !
