### ISSUE TITLE
Node failed to start! Error: Not able to start from state: uninitialized

### ISSUE THREAD

**Issue by sorleone** [ipfs/js-ipfs#1507]
The following code produces an error with version 0.31.4. I'd like to have the `ipfs.on.('ready'` event promisified, and the quickest way to get it seems to be calling the `start()` method but that gives me an error.

```
const IPFS = require('ipfs');

const ipfs = new IPFS({
  start: false
});

ipfs.start()
  .then(() => console.log('Node started!'))
  .catch(error => console.error('Node failed to start!', error))
```

**Comment by alanshaw** [comment]
The ready event is fired when the node is ready to be interacted with, so even if you don't start the node you still need to wait for it to be ready. This is because there are async initialization tasks that need to be performed that happen before the node is started.

If you want to promisify the `ready` event I'd do something like this:

```js
const ipfsReady = ipfs => new Promise((resolve, reject) => {
  ipfs.on('ready', () => {
    ipfs.removeListener('error', reject) // remove error listener so future errors aren't swallowed
    resolve(ipfs)
  })
  ipfs.on('error', reject)
})

const ipfs = await ipfsReady(new IPFS())
```

Hope that helps 😄
