### ISSUE TITLE
File added right after 'ready' event doesn't get announced to DHT

### ISSUE THREAD

**Issue by jhiesey** [ipfs/js-ipfs#1526]
- **Version**: 0.31.7
- **Platform**: Darwin Johns-MacBook-Pro-4.local 17.7.0 Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64 x86_64
- **Subsystem**: libp2p (maybe)

#### Description:
When I enable the DHT and disable prefetch in the ipfs-101 example, the added file is not advertised through the DHT and is thus not visible to other nodes. This is happening because `dht.provide()` is called before any peers are available, so the call to `dht.getClosestPeers()` fails. The following appears in the logs:

```
  libp2p:dht:QmeKMaZs getClosestPeers to  �|?�Q��Q��0��ܠ����o��Ϥ�Xf� +3ms
  libp2p:dht:query: �|?�Q��Q��0��ܠ����o��Ϥ�Xf�:QmeKMaZs:error Running query with no peers +0ms
```

Adding a few seconds of delay before calling `node.files.add()` fixes the issue.

I'm not sure where this should be fixed (even ipfs vs libp2p), but the DHT shouldn't be used before it's ready to accept queries.

#### Steps to reproduce the error:

1. Clone modified example at https://github.com/jhiesey/js-ipfs/blob/dht-test/examples/ipfs-101/1.js
2. Edit string on line 31 to be unique
3. Run `DEBUG="libp2p:dht*" node 1.js`
4. Note error in console about dht query with no peers
5. Try `ipfs cat /ipfs/<hash>` on another node. It hangs forever.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
