### ISSUE TITLE
Fails to start for the first time due to 'datastore key does not have a valid format'

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#1615]
- **Version**: 0.32.3
- **Platform**: ipfs-companion in Firefox and Chrome
- **Subsystem**: looks like related to newly added IPNS

#### Description:

After switching from js-ipfs `0.31.7` to `0.32.3` switching to embedded node in companion  produces an error:

> ![2018-10-04--01-23-32](https://user-images.githubusercontent.com/157609/46444933-9c775480-c774-11e8-8777-9a3d9d4790cc.png)

What is interesting, is that if I switch to External node and then back again to Embedded one, second time js-ipfs tries to initialize is  successful and everything works as expected. 

I did not look into it deeper, but my guess is that there is  some sort first-run init that happens after the error occurs that fixes datastore(?) and makes following runs in the same context to work fine. Maybe IPNS tries to publish key before it is stored or something?

cc @vasco-santos  in case its something obvious 

#### Steps to reproduce the error:

To build Companion with js-ipfs v0.32.3 and run in Firefox (but the same issue is in Chromium):

1. `git clone https://github.com/ipfs-shipyard/ipfs-companion.git`
1. `cd ipfs-companion`
1. `git reset --hard  21eb92bee2b8ea99daa3fb1836431bd63f047c24`
1. `npm run dev-build`
1. `npm run firefox`

Then, go to _Preferences_ and switch to _Embedded_ node. Initial try will fail, following ones will succeed.

**Comment by vasco-santos** [comment]
Hey @lidel 

I see the problem. Basically, there should be a mismatch of versions for `interface-datastore` in the dependencies. This causes this [condition](https://github.com/ipfs/js-ipfs/blob/master/src/core/ipns/publisher.js#L93) to happen. 

But let's fix this in the correct way! I will create a PR for `interface-datastore` to add the `class-is` module and use it instead of the `instance of`.

**Comment by alanshaw** [comment]
@vasco-santos / @lidel can this be closed now?

**Comment by lidel** [comment]
@alanshaw I think we are waiting for https://github.com/ipfs/js-ipfs/pull/1617

**Comment by vasco-santos** [comment]
We just need [interface-datastore#24](https://github.com/ipfs/interface-datastore/pull/24) to get released and then update the `js-ipfs` PR. @diasdavid can you release it?

**Comment by pgte** [comment]
Also bumping into this issue here: https://github.com/ipfs-shipyard/peer-star-app/pull/95

**Comment by diasdavid** [comment]
@pgte I believe @vasco-santos fixed this yesterday, to get the fix you need a fresh npm install of your modules

**Comment by vasco-santos** [comment]
In this case, @pgte since you are already updating `interface-datastore`, `datastore-core` and `ipfs-repo`, you will need to wait for [js-ipfs#1617](https://github.com/ipfs/js-ipfs/pull/1617) to get merged and released (which solves this issue). 

In the meanwhile, if you do not upgrade those package versions, I think that it will work fine for you.
