### ISSUE TITLE
Resolve  ipns on browser side

### ISSUE THREAD

**Issue by mullerivan** [ipfs/js-ipfs#1644]
HI there, That is a grate  app im working on some test that  intent to resolve in client/browser side  a  static IPNS with something  like

```
<script src="https://unpkg.com/ipfs/dist/index.js"></script>


const node = new Ipfs({
        EXPERIMENTAL: {
            pubsub: true // required, enables pubsub
        },
        repo: 'ipfs-' + Math.random(),
        config: {
            Addresses: {
                Swarm: [
                    '/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star'
                ]
            }
        }
    });
node.once('ready', () => {})

result = node.resolve('/ipns/IPNS-HASH',
node._peerInfo.id,{local:false,recursive=true},
function (err) {console.log(err)})

```

Any idea  how is the  proper  way to call ipns to resolve an static  hash and  give  me back the  last updated hash of the  curren file?

**Comment by alanshaw** [comment]
Soon™️. IPNS doesn't have a complete implementation in js-ipfs just yet. It is being worked on right now ([IPNS over pubsub](https://github.com/ipfs/js-ipfs/pull/1559)). Also, one of ways of resolving IPNS names is via the DHT which is also [being worked on](https://github.com/ipfs/js-ipfs/pull/856) so that it is interoperable with go-ipfs.

You can also use [`ipfs.name.resolve`](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/NAME.md#nameresolve) to resolve an IPNS name to a hash but currently this only works for keys you've published locally (so not much good for application use atm).

`ipfs.resolve` has not been updated yet to work with IPNS, and can currently only be used to lookup hashes for IPFS paths. See the [0.32 release docs for more info](https://github.com/ipfs/js-ipfs/releases/tag/v0.32.0).

**Comment by kuabhish** [comment]
Hey @alanshaw , I am unable to work with ipns, 

I am publishing a static file(i.e. ipfs/<hash>) to ipns 
and I am getting some name , value pair . 

then, when i try to fetch it.:
```
ipfs resolve -r /ipns/QmW5VYrjip26PC3ni6ML8TnbQULU7RJqSr6KiEH6TDQ5ca: context deadline exceeded
```

I see this.. 

How can i resolve this. ?

**Comment by lukecage0** [comment]
Please try
$ipfs name resolve QmW5VYrjip26PC3ni6ML8TnbQULU7RJqSr6KiEH6TDQ5ca

**Comment by mullerivan** [comment]
@lukecage0  are you sure  that this is JS code? looks  like bash commands

:)
