### ISSUE TITLE
DIAL to every peers in WantManager when get a hash ?

### ISSUE THREAD

**Issue by LiMoMoMo** [ipfs/js-ipfs#1698]
- **Version**: 0.32.3
- **Platform**: 
- **Subsystem**: bitswap

#### Type:
Question

#### Severity:
Very Low
#### Description:
i added output in the `libp2p` module to figure out how it works.
i found that when i fetch a date(get(hash)), the `libp2p` dial to every peers that it connected.
the `libp2p.network.findProviders(cid, maxProviders, callback)` reveive paragrams to restrict the provider per request, but if when the `dht` is not enable, the paragrams input is not useful.

the `signal-server` in my demo has only 5 or 6 peers connected, its OK. But if the server connected by 
hundreds nodes, connect to every nodes in the net may cause heavy performance burden.

**Comment by alanshaw** [comment]
@jacobheun does this sound like expected behaviour?

**Comment by jacobheun** [comment]
So currently `maxProviders` isn't passed to the content providers in libp2p as it's not yet supported. A default time is passed https://github.com/ipfs/js-ipfs-bitswap/blob/v0.21.0/src/network.js#L105, which is currently 10 seconds. So assuming you find 100 providers in that 10 seconds, you'd try to connect to all of them.  

This is the expected behavior, but we should probably look at adding support for maxProviders before we start turning on the dht by default. cc @vasco-santos

**Comment by alanshaw** [comment]
@LiMoMoMo does that answer you question?

**Comment by jacobheun** [comment]
FYI: we now support the improved options in libp2p 0.24 and the latest kad-dht. I've got a PR for bitswap, https://github.com/ipfs/js-ipfs-bitswap/pull/183, to update the call. Hopefully we can get this into the js-ipfs 0.34 release.

**Comment by LiMoMoMo** [comment]
> @LiMoMoMo does that answer you question?

yes, thank you !
