### ISSUE TITLE
Transfering data between two local peers is slow

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs#1709]
- **Version**: 0.33.1
- **Platform**:  Linux

#### Description:

Run two connected peers locally. Add a file to one of them. Then request that file from the other peer. That is quite slow. On my machine around 8s for a 100MB file. If I do a subsequent request (the file is basically in memory) it takes around 800ms.

#### Steps to reproduce the error:

Create a new temporary 100MB file called `/tmp/100m.bin`. I use

    head -c 100MB /dev/zero|openssl enc -aes-128-cbc -pass pass: -nosalt > /tmp/100m.bin

for that as it always produces the same bytes.

Install pretty-hrtime and js-ipfs along with this file:

    npm install pretty-hrtime ipfs

Run the whole thing (use the script from below):

    node index.js

You should see an output like

    It took: 8.74 s

A second run should be way faster (800ms or so).
In order to get a cold cache again, just remove `/tmp/peerb` and run
the script again, it should be around the original timing again.

In the past I was able to reduce the time significantly with increasing the data [Bitswap is sending at once](https://github.com/ipfs/js-ipfs-bitswap/blob/6eda9b0f44841251a3266347f9554eab0165517f/src/decision-engine/index.js#L21). Hence I think it has something to do with recreating the connections all the time (though I've no proof for that). BTW: I tried to increase the `MAX_MESSAGE_SIZE`t again today, now it just makes things not working anymore. I don't have the time to dig deeper into this atm.

```js
'use strict'

const fs = require('fs')
const prettyHrtime = require('pretty-hrtime')
const IPFS = require('ipfs')

const peerAPromise = new Promise((resolve) => {
  const config = {
    "Addresses": {
      "API": "/ip4/127.0.0.1/tcp/5012",
      "Gateway": "/ip4/127.0.0.1/tcp/9091",
      "Swarm": [
        "/ip4/0.0.0.0/tcp/4012",
        "/ip4/127.0.0.1/tcp/4013/ws"
      ]
    },
    "Bootstrap": []
  }
  const peer = new IPFS({
    repo: '/tmp/peera',
    config: config,
    init: {
      emptyRepo: true
    }
  })
  peer.on('ready', () => {
    console.log('peerA ready')
    resolve(peer)
  })
})

const peerBPromise = new Promise((resolve) => {
  const config = {
    "Addresses": {
      "API": "/ip4/127.0.0.1/tcp/5022",
      "Gateway": "/ip4/127.0.0.1/tcp/9092",
      "Swarm": [
        "/ip4/0.0.0.0/tcp/4022",
        "/ip4/127.0.0.1/tcp/4023/ws"
      ]
    },
    "Bootstrap": []
  }
  const peer = new IPFS({
    repo: '/tmp/peerb',
    config: config,
    init: {
      emptyRepo: true
    }
  })
  peer.on('ready', () => {
    console.log('peerB ready')
    resolve(peer)
  })
})

const connectPeers = async (peerA, peerB) => {
  try {
    const peerAId = await peerA.id()
    return peerB.swarm.connect(peerAId.addresses[0])
  } catch (err) {
    console.error(err)
  }
}

const main = async () => {
  try {
    const peerA = await peerAPromise
    const peerB = await peerBPromise

    await connectPeers(peerA, peerB)
    console.log('vmx: connected')

    // Insert into peerA
    const fileStream = fs.createReadStream('/tmp/100m.bin')
    const inserted = await peerA.files.add(fileStream)
    console.log('vmx: inserted:', inserted)

    // peerB doesn't any data cached, get all from peerA
    const start = process.hrtime();
    await peerB.files.cat(inserted[0].hash)
    const end = process.hrtime(start);
    console.log('It took:', prettyHrtime(end))

    peerA.stop()
    peerB.stop()
  } catch (err) {
    console.error(err)
    process.exit(1)
  }
}

main()
```

**Comment by mikeal** [comment]
For analyzing these issues we should create something of a "Macro" level view of performance. Off the top of my head, it would look something like:

* Network Establishment
  * Peer Discovery
  * Connection Establishment
* Data Replication
  * This is where things get complicated because concurrency starts to effect whether or not certain things we *spend time on* actually contribute to performance issues that are visible to the user. If you look at the "Network" tab in Web Inspector you'll see a visualization that shows which requests are dependent on prior requests and which are effectively done in parallel, this is basically what I'm talking about.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
