### ISSUE TITLE
Prevent mfs corruption

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#1743]
I think we need a mechanism for `js-ipfs` components to prevent the process from exiting until they've finished a bit of critical work (could show a `CTRL-C to force quit` kind of message).

My concern is that if `mfs` is interrupted while writing the root hash to the level datastore, it'll potentially not be able to read the hash on the next startup which would show the user an empty directory.

**Comment by alanshaw** [comment]
> Received interrupt signal, shutting down...
> (Hit ctrl-c again to force-shutdown the daemon.)

Like go-ipfs?

**Comment by grantlouisherman** [comment]
Hey @alanshaw could I take this one?

**Comment by alanshaw** [comment]
@grantlouisherman you are welcome to have a go at this, but the issues labelled "help wanted" might be slightly more appropriate for new contributors https://github.com/ipfs/js-ipfs/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

In particular I'd love to see https://github.com/ipfs/js-ipfs/issues/1867 implemented.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
