### ISSUE TITLE
js-ipfs potentially leaking sprintf and vsprintf to global scope?

### ISSUE THREAD

**Issue by aphelionz** [ipfs/js-ipfs#1836]
- **Version**: 0.34.2
- **Platform**: Node.js
- **Subsystem**: Automated tests

#### Description:
When running the automated tests for https://github.com/orbitdb/ipfs-log, 

#### Steps to reproduce the error:
```bash
git clone https://github.com/orbitdb/ipfs-log
glt checkout feat/js-ipfs-0.34
```

Then remove comment out line 17 in `test/browser/index.html`
```javascript
// mocha.setup({globals: ['sprintf', 'vsprintf']});
```

Then run the following command
```
make rebuild
```

It should result in a global leak error:

```
1) Entry - Persistency (js-ipfs)
      "before all" hook:
    Error: global leaks detected: sprintf, vsprintf
```

**Comment by aphelionz** [comment]
@alanshaw et al, any updates on this? I'd love to get `ipfs-log` up to 0.34

**Comment by alanshaw** [comment]
Looks like this was [fixed in `sprintf-js` v1.1.1](https://github.com/alexei/sprintf.js/commit/180a8a65554bce5d4963908cddeeff3b00cc7cc0) and it's used in [`ip-address`](https://github.com/beaugunderson/ip-address) which currently depends on the previous version:

```
└─┬ libp2p-tcp@0.13.0
  └─┬ ip-address@5.8.9
    └── sprintf-js@1.1.0 
```

When `ip-address` is updated this should be resolved (assuming they release a minor or patch version).

**Comment by aphelionz** [comment]
Thanks @alanshaw

**Comment by aphelionz** [comment]
Also created an issue with `ip-address` https://github.com/beaugunderson/ip-address/issues/82

**Comment by aphelionz** [comment]
This was just closed https://github.com/beaugunderson/ip-address/issues/82 and `ip-address` is npm published to 5.9.0!

**Comment by aphelionz** [comment]
Re-open?

**Comment by alanshaw** [comment]
> Re-open?

?
