### ISSUE TITLE
--read-timeout option for `ipfs get`

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#1845]
See https://github.com/ipfs/go-ipfs/issues/5541

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out! Helia and newer js ipfs libraries usually support AbortSignals for things like this. If there is something more specific needed, please let us know.
