### ISSUE TITLE
WebRTC peer discovery not finding providers in DHT

### ISSUE THREAD

**Issue by cryptoquick** [ipfs/js-ipfs#1942]
Hello, I'm currently working on getting the following configuration working:

[freeweb/index.ts at master · cryptoquick/freeweb · GitHub](https://github.com/cryptoquick/freeweb/blob/master/src/ipfs/index.ts)

When opened in different browsers, the different peers are able to dial each other, but when looking for each other on DHT, they completely miss. In particular, after adding a file in one browser, and catting in another, the connection doesn't seem to work. I see in debug the following text: `libp2p:dht:query:*:*:error Running query with no peers`. This made me think something is wrong with KadDHT or the peer discovery interface. After more research, I noticed a number of current issues where the peer walk algorithm is currently disabled, in favor of work towards an adaptive strategy of some kind currently present in go-ipfs. Until that work is finished, however, I tried some versions that pre-date those issues:

- ipfs: 0.35.0-pre.0
- libp2p: 0.25.0-rc.3
- libp2p-kad-dht: 0.14.6
- libp2p-webrtc-star: 0.15.8

The supposition being, what I'm trying to accomplish likely worked before some activity of some sort. I suppose I'm asking, what needs to be done in order to make this work, even locally, regardless of NAT? Or am I missing something, doing something wrong, or making an improper assumption?

(Posting in the main IPFS repo due to the number of IPFS/libp2p projects this concerns, and because I'm using the IPFS interface, which tests a lot more functionality than just libp2p.)

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
