### ISSUE TITLE
[Feature] Add Proxy Support

### ISSUE THREAD

**Issue by ghbjklhv** [ipfs/js-ipfs#2173]
**Feature**: Add [Proxy](https://www.wikipedia.org/wiki/Proxy_server) Support
**Why?**: Adding proxy support may enable users to route connections through another server  to provide better anonymity. Plus, it would enable users to utilize IPFS with [TOR](https://www.wikipedia.org/wiki/Tor_(anonymity_network)).

_________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75313167-feature-add-proxy-support)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75313167)](https://www.bountysource.com/issues/75313167-feature-add-proxy-support)

**Comment by alanshaw** [comment]
@ghbjklhv I'm moving this feature request to libp2p as this is where the development would need to happen.

**Comment by alanshaw** [comment]
@jacobheun I'm not able to transfer this issue to `js-libp2p`. Is this of interest? Should @ghbjklhv open an issue there instead?

**Comment by jacobheun** [comment]
I would recommend moving this to https://github.com/libp2p/libp2p to have the broader discussion about proxy support for libp2p as a whole, so that if a path forward is decided, we can role that into a spec so that each supported implementation behaves the same way.

I can't move the issue, so it would need to be reopened there.

**Comment by alanshaw** [comment]
SGTM - @ghbjklhv would you mind opening an issue there so the discussion can begin? 🙏
