### ISSUE TITLE
addFromURL() Not Following Redirects

### ISSUE THREAD

**Issue by leoherzog** [ipfs/js-ipfs#2314]
Hello!

I'm running this in NodeJS:

```lang-js
const ipfs = require('ipfs');
const node = new ipfs();
node.addFromURL("http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1810.iso", (error, result) => {
  if (error) {
    console.log(error.message);
  }
  console.log("Added " + result[0].path + " to IPFS - " + result[0].hash);
});
```

I get the hash almost right away, but it looks like js-ipfs is adding that HTML page to IPFS, not the ISO. I'm confused by this, because I thought that [js-ipfs was supposed to follow redirects](https://github.com/ipfs/js-ipfs-http-client/issues/513). If I `wget` that same URL, it `302 Redirect`s to a mirror. Help?

**Comment by alanshaw** [comment]
Visiting that URL in a browser returns a 200 and a HTML page, so there's probably some header that `wget` is sending that's causing `isoredirect.centos.org` to redirect. Either that or `isoredirect.centos.org` is doing some user agent sniffing. If it's the former then I'd appreciate a PR to fix it but if it's the latter then there's not anything we can do about it (since `User-Agent` is a restricted header in the browser that we can't change).

Do you have any time to look into this further?

**Comment by leoherzog** [comment]
Aha. Further investigation: If I request `"http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1810.iso"` with the user agent `"Wget/"`, sure enough, I get redirected. I guess they're doing some sniffing. ¯\_(ツ)_/¯
