### ISSUE TITLE
webui and ipfs-desktop do depend on js-ipfs/js-ipfs-http-api

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs#2542]
From https://github.com/ipfs/js-ipfs/blob/master/docs/RELEASE_ISSUE_TEMPLATE.md

<img width="694" alt="image" src="https://user-images.githubusercontent.com/1211152/66941211-467df380-effb-11e9-8436-4560d821b5c4.png">

I don't believe this is correct. Because:

- webui depends on ipfs-redux-bundle, which depends on js-ipfs-http-client
- ipfs-desktop depends on js-ipfsd-ctl that uses js-ipfs-http-client

also:

- js-ipfs does expose webui to its users through its own http gateway.

**Comment by achingbrain** [comment]
These modules need to declare which versions of IPFS and/or the HTTP API client they are compatible with, even if it's just for their tests, otherwise they risk depending on features that may not be available at runtime and suffering other hard to replicate bugs.  cc @hacdias @olizilla 

## webui

We could add [`ipfs-redux-bundle`](https://github.com/ipfs-shipyard/ipfs-redux-bundle) to our external repo testing since it has a direct dependency we can swap out?

Otherwise the [webui end to end tests](https://github.com/ipfs-shipyard/ipfs-webui/blob/master/test/e2e/navigation.test.js#L49-L73) could be configured to run against an actual IPFS instance, the version of which is declared in `package.json` which would also let us run them against `js-IPFS` PRs/releases as part of CI.

## ipfs-desktop

This module should pass a known version of `ipfs-http-client` to `ipfsd-ctl`, then we can add it to our external repo testing.

If it just takes whatever `ipfsd-ctl` happens to be bundled with, then it's the [wild west](https://github.com/ipfs/js-ipfsd-ctl/issues/374).

## webui on the gateway

> js-ipfs does expose webui to its users through its own http gateway.

This is true, but we resolve the `CID` of a released version*, so assume that some testing has taken place prior to the PR to `js-IPFS` updating the `CID` was submitted, in the same way that we accept other dependency updates.

This is a gap though, maybe we could figure out a way of running the webui tests with the current branch head as part of a release.  Might involve doing something clever with `connect-deps` and `ipfs-redux-bundle` or the e2e test refactor suggested above.


----

* = recently [changed](https://github.com/ipfs/js-ipfs/pull/2520) to an IPNS name, probably going to [change back](https://github.com/ipfs/js-ipfs/pull/2520#issuecomment-542160280) to a CID

**Comment by achingbrain** [comment]
@hacdias @olizilla any thoughts on this?  Specifically about changing webui/desktop to test against an actual version of `js-ipfs` that we can swap out during CI.

**Comment by hugomrdias** [comment]
We should only tests direct dependents!! 
For webui we should only tests ipfs-redux-bundle
For desktop it should declare ipfs and http-client and pass those on to ipfsd-ctl (this should be best practice to use ctl the new version I'm working on will have this first thing in the readme) and then we can test it directly.

**Comment by SgtPooki** [comment]
FYI that this issue is no longer relevant since we're pulling js-ipfs out of webui and desktop. closing this.

cc @tinytb @achingbrain
