### ISSUE TITLE
node.key.gen('name', { type: 'ed25519', size: 256 }) does not work

### ISSUE THREAD

**Issue by Bluebie** [ipfs/js-ipfs#2553]
- **Version**: { version: '0.38.0', repo: 7, commit: '' }
- **Platform**: macOS Catalina (nodejs v12.12.0 via Homebrew)
- **Subsystem**: libp2p-keychain?

#### Type:
Bug

#### Severity:
Medium

#### Description:
despite documentation, js-ipfs does not support generating ed25519 keys. libp2p-keychain throws an error that ed25519 keys do not have an `export` function when `ipfs.key.gen` is called

#### Steps to reproduce the error:
```
> const IPFS = require('ipfs'); let ipfs = (new IPFS({ pass: "01234567890123456789" }))
> ipfs.key.gen('ed', { type: 'ed25519', size: 32 })
Promise { <pending> }
> Thrown:
TypeError: keypair.export is not a function
    at ./node_modules/libp2p-keychain/src/keychain.js:215:25
    at ./node_modules/libp2p-crypto/src/keys/ed25519-class.js:97:7
```

**Comment by achingbrain** [comment]
I think this is because the underlying `libp2p-crypto` module can't export `ed25519` keys in the pem format, because the underlying `node-forge` module [doesn't support it](https://github.com/digitalbazaar/forge/issues/667), though they [are accepting pull requests](https://github.com/digitalbazaar/forge/issues/576#issuecomment-383125842).

**Comment by achingbrain** [comment]
More discussion here: https://github.com/libp2p/js-libp2p-crypto/issues/145

**Comment by alanshaw** [comment]
I've updated the JS core interface documentation to clarify the situation https://github.com/ipfs/interface-js-ipfs-core/pull/549

**Comment by jacobheun** [comment]
Fixed in https://github.com/ipfs/js-ipfs/pull/3212
