### ISSUE TITLE
Consider dialing to the pinners on bootstrap

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs#2568]
js-ipfs could dial directly to the pinners (IPFS Cluster nodes) on bootstrap, increasing the chance of being connected to the node with the content we are looking for. The addrs are:

```
		"/ip4/138.201.67.219/tcp/4001/ipfs/QmUd6zHcbkbcs7SMxwLs48qZVX3vpcM8errYS7xEczwRMA",
		"/ip4/138.201.67.220/tcp/4001/ipfs/QmNSYxZAiJHeLdkBg38roksAR9So7Y5eojks1yjEcUtZ7i",
		"/ip4/138.201.68.74/tcp/4001/ipfs/QmdnXwLrC8p1ueiq2Qya8joNvk3TVVDAut7PrikmZwubtR",
		"/ip4/94.130.135.167/tcp/4001/ipfs/QmUEMvxS2e7iDrereVYc5SWPauXPyNwxcy9BXZrC1QTcHE",
```

**Comment by achingbrain** [comment]
Sounds good - should be a case of just adding them to the `Bootstrap` list in the default config, right?  

Are they listening on `wss` for browser clients?

**Comment by daviddias** [comment]
> Sounds good - should be a case of just adding them to the Bootstrap list in the default config, right?

Exactly

> Are they listening on wss for browser clients?

I don't think so, yet. @hsanjuan, @olizilla will be the ones capable of clarifying (or making them listen on wss :))

**Comment by olizilla** [comment]
I'm mildly against making the cluster nodes have both storage and bootstrap responsibilities. Also this would make js-ipfs better at finding content for those who have permission to pin on cluster, but no one else, which seems a little awkward.

Perhaps we should be talking about re-uniting the gateways, bootstrap and preload nodes until we have delegated routing and dht and dht perf improvements. I'm not hugely in favour of that either but it seems like it could improve perf for all users.

**Comment by achingbrain** [comment]
I guess it also introduces more reliance on our centralised infrastructure which doesn't seem in the spirit of the game.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia).  You can [learn more about this deprecation](https://github.com/ipfs/js-ipfs/issues/4336) and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).  

Please feel to reopen with any comments by 2023-06-02.  We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

We probably don't want to increase our dependence on centralized infra, otherwise we would probably make a PR to https://github.com/ipfs/helia/blob/main/packages/helia/src/utils/bootstrappers.ts

Note: users should be encouraged to add their own known & persistent backend nodes to their bootstrap list and not depend only on bootstrap nodes provided by PL or libp2p infra.
