### ISSUE TITLE
How do I add a directory in JS?

### ISSUE THREAD

**Issue by mikeal** [ipfs/js-ipfs#277]
I'm playing around with the `ipfs.files` API. I looked through the tests but I can't find an equivolent for `ipfs add -r` to add a directory.

I also just generally can't figure out how to programmatically create a new directory and add/link files into it.

**Comment by diasdavid** [comment]
Hey @mikeal, good to see you around here! :)

The module that gets exported by js-ipfs is the "core part of IPFS", which doesn't touch the file system directly. You can add a directory recursively by adding a stream of objects with the following signature `{ path: "/a/b/c", stream: "readable stream with the content of the file"}`

You can take a peak at how the js-ipfs cli (what you get if you install the module globally) does it here:

https://github.com/ipfs/js-ipfs/blob/master/src/cli/commands/files/add.js#L62-L92

The interface is not the best, yet. We are currently updating it and standardising it between js-ipfs core and js-ipfs-api (our http client library) so that you can use a js-ipfs node or a remote node (like go-ipfs) without having to change the app. You can read the 'soon to be' API here https://github.com/noffle/interface-ipfs-core/blob/8c5eeb5591aa2378301911fe9f3a965322b529ca/README.md

**Comment by yehia67** [comment]
Hey, I want to upload a directory is it available now using  JavaScript? or if I will update each file on the directory,Do you have any idea how to link all file hashes with only one hash to access them? @daviddias  @mikeal

**Comment by yehia67** [comment]
I tried this code:
```
 ipfs.addFromFs('/home/yehia/Documents/openclassroom projects/quoate generator', { recursive: true, ignore: ['subfolder/to/ignore/**'] }, (err, result) => {
            if (err) { throw err }
            console.log(result)
        })
```

but it gave me this error

![Screenshot from 2019-08-08 14-49-45](https://user-images.githubusercontent.com/21314724/62704501-df850280-b9eb-11e9-9c97-8c89cba7579f.png)

**Comment by daviddias** [comment]
@yehia67 that's a browser limitation, it doesn't note have access to the file system of your Operating System and therefore you have to upload the file into the browser context in a more traditional way.

See this complete tutorial at https://github.com/ipfs/js-ipfs/tree/master/examples/exchange-files-in-browser

**Comment by yehia67** [comment]
Okay Thanks @daviddias

**Comment by JithinKS97** [comment]
Hello, is the webkitdirectory supported yet? @mikeal
