### ISSUE TITLE
Tracking issue for `ky` removal

### ISSUE THREAD

**Issue by hugomrdias** [ipfs/js-ipfs#2801]
ky has problems with node 13, clones responses https://github.com/ipfs/js-ipfs-http-client/blob/master/src/lib/error-handler.js#L12

Related:
https://github.com/ipfs/js-ipfs-http-client/issues/1117#issuecomment-589011968
https://github.com/ipfs/js-ipfs-http-client/pull/1224#issuecomment-589220724 this needs to be patched in react-native not here
https://github.com/ipfs/js-ipfs-http-client/issues/1219#issuecomment-582846315
https://github.com/ipfs/js-ipfs-http-client/pull/1224

**Comment by pcowgill** [comment]
@hugomrdias Will this behavior from `ky` be preserved `Treats non-2xx status codes as errors`?

**Comment by sholladay** [comment]
Hey, Ky maintainer here. I wanted to see if there is something we could do to make Ky easier to use or better in some way? Looks like you had to re-implement some of Ky's behavior, which is unfortunate. Maybe we could provide an option related to cloning responses? If there are any other bugs that lead to this, I'd love to take a look and fix those since they were blockers for you and might be for other projects, too.
