### ISSUE TITLE
Explain best practices for using this package since the default export contains new ES features

### ISSUE THREAD

**Issue by pcowgill** [ipfs/js-ipfs#2841]
An info to the README about why a client using this package might want to do the transpiling for their own target envs (I agree there are good arguments for this, but many devs won't be used to this newer pattern), plus instructions on how best to do that (Babel config, etc.) given the use of newer ES features in this package like async iterators.

Thanks!

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out! There are helia examples in the ipfs-examples/helia-examples repo you can reference for your transpiling & bundler-config needs.
