### ISSUE TITLE
p2p commands are not supported

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/js-ipfs#2843]
The `p2p` command (https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#ipfs-p2p) is available in go-ipfs since the 0.4.10 version. If supported in js-ipfs-api this could be very useful to implement custom protocols on top of ipfs.

For Arbore (https://github.com/MichaelMure/Arbore) I would use it to replace the pubsub in 1-to-1 communications.

**Comment by zot** [comment]
The chat example is ready to play with (still a bug with certain disconnecting in the example but plan to fix that soon).

I renamed the project: https://github.com/zot/libp2p-websocket

I had plenty of false starts and difficulties with circuit relay and I found that pubsub takes a very long time, causing startup delays of a minute or more. I plan to investigate this over time but for now I just hacked my own application-level relay in JavaScript so that a browser can function as a relay.

Anyone interested can check out the project and please post issues if you have problems

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia via another method or function. Please let us know if it's not!
