### ISSUE TITLE
Consider renaming the DHT API endpoint

### ISSUE THREAD

**Issue by Stebalien** [ipfs/js-ipfs#2890]
So, it may cause too much churn to fix this but... the DHT is just one implementation of a routing system. Really, the DHT command encompasses:

1. Content routing.
2. Peer routing.
3. The "record store".

It would be kind of nice to either just call this interface the routing interface or use three independent interfaces.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
