### ISSUE TITLE
Maybe there should be a way for pin rm command not to throw an error when object is not pinned

### ISSUE THREAD

**Issue by mitar** [ipfs/js-ipfs#2892]
Otherwise currently user has first to check if object is pinned, if they just try to forget about an object fully.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

@achingbrain I believe this is /migration-available but assigning to you because I think there's some useful info here.

**Comment by achingbrain** [comment]
Closing as not planned.

If you want to check to see if an object is pinned before removing the pin, you can call `helia.pins.ls({ cid })`.

Helia does not support removing multiple pins at once, you can invoke `helia.pins.rm` repeatedly and deal with the errors as they occur.
