### ISSUE TITLE
Improving the Block API

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs#2898]
I think the Block API should be improved so that IPFS can be used a a proper blob storage.

For considering it "proper" I would say it needs:

 - Pinning support
 - Remove operation
 - Bulk operations to put, get and remove several blocks at the same time (that might even be the only API, where single blocks are a special case of
 - Probably a size limit per block, so that it can always be transferred to other peers via Bitswap

**Comment by achingbrain** [comment]
Some good ideas in here that need breaking out into smaller pieces.

The user can orchestrate existing APIs for pinning and `block.rm` exists, but the following would be useful:

* streaming (bulk) operations
* size limits

**Comment by mikeal** [comment]
Would pinning a block mean “pin only this block and not the entire graph?”

**Comment by achingbrain** [comment]
That's the way I read it, though it seems a bit low level for IPFS.

**Comment by achingbrain** [comment]
Having said that, the user can pin 'directly' - it's not the default but is basically pinning only a block and not the whole graph.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
