### ISSUE TITLE
Find testing strategy for tests that are using DNS

### ISSUE THREAD

**Issue by victorb** [ipfs/js-ipfs#2899]
Multiple tests around in our ecosystem assumes there is a dns resolver that has a connection to the internet. The dependency on internet backbone is something we want to avoid in general, and also we want to make sure the tests are always working as expected.

One idea is to run a local dns server for the process where the tests are running, to use. Then we can setup whatever records we want, and resolve them via `.home` for example.

Comes from https://github.com/ipfs/interface-ipfs-core/pull/332#issuecomment-406539315

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!

related to ipfs/js-ipfs#2000 ipfs/helia-ipns#53
