### ISSUE TITLE
Resolution commands rework

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs#2900]
From https://github.com/ipfs/go-ipfs/issues/5635:

> 1. `ipfs name resolve` and `ipfs dns` should be recursive by default, the current behavior is a surprising foot-gun. We should consider just changing this as I'm sure it'll fix _significantly_ more bugs than it causes.
> 
> 2. `ipfs dns` should resolve up to the first non-dnslink path by default. It shouldn't return an _error_ when it hits a non-dnslink path, it should just _return_ that path.
> 
> 
> I'd also like to return a partial result when we hit the recursion limit (along with the error) but that's less pressing.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
