### ISSUE TITLE
Config Set: Test isolation / validation

### ISSUE THREAD

**Issue by travisperson** [ipfs/js-ipfs#2902]
Currently `.config.set should fail on non valid value` is the only test that does not run in isolation (from `js-ipfs-api` under `go-ipfs v0.4.15` :tada:)

However, I don't believe it's really testing what we want it to be testing. It appears it's trying to produce an error by passing an invalid type, similar to the `non valid key` test above it.

https://github.com/ipfs/interface-ipfs-core/blob/ef910266b36c89fe21f9821f86bdb9955d60b468/js/src/config/set.js#L75-L87

The issue is that a `Buffer` [does not raise this error, as `typeof <Buffer>` is `object`](https://github.com/ipfs/js-ipfs-api/blob/a8f9a43064930c816b0e73dbc1674a313cf1baca/src/config/set.js#L15-L19). It also passes JSON serialization. The only reason this test passed was because the daemon it self rejected the type due to being set by a prior test.

https://github.com/ipfs/interface-ipfs-core/blob/ef910266b36c89fe21f9821f86bdb9955d60b468/js/src/config/set.js#L32-L41

I don't believe this is what is expected to be under test though.

* In here I think we need to update the assertions to expect something more specific.
* `js-ipfs-api` probably needs to reject buffers.
   - It should also probably match [`js-ipfs-repo`](https://github.com/ipfs/js-ipfs-repo/blob/a7ea45bac6f1c264f86e79357f702314758a48f1/src/config.js#L56-L73)

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterwards (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
