### ISSUE TITLE
pin ls could return also sizes of pinned objects

### ISSUE THREAD

**Issue by mitar** [ipfs/js-ipfs#2906]
So it could be easier to get a grasp of storage requirements of pinned objects.

**Comment by jakehemmerle** [comment]
I'll claim this

**Comment by jakehemmerle** [comment]
@daviddias @whyrusleeping I observed a few files and folders and it appears the most straightforward (although not the most accurate) way to calculate object size is to use the CumulativeSize value from 'node bin.js object stat $ROOT_CID'. Below is are some files/folders I tested and their CumulativeSize value:

1.9 kB file (4 kB on disk): 2007 (~5% off)
9 B file (4 kB on disk): 17 (super small)
97.4 kB folder (446 kB on disk): 105051 (~10% off)
10.7 MB folder (15.1 MB on disk): 58867739 (500% off, but less than factor of 10)

It appears 'the size of the object itself' is different from 'the space it takes on disk'.

I think using CumulativeSize solves the use case of 'grasping the storage requirements of a pinned object', since to me this seems like a 'ballpark' metric, but does not accurately represent the space it will take up on a drive. Should I proceed with pretty printing the CumulativeSize value or use another metric?

**Comment by jakehemmerle** [comment]
@achingbrain @daviddias

not sure who to ping

**Comment by jakehemmerle** [comment]
@whyrusleeping

**Comment by achingbrain** [comment]
I think this is straightforward for `dag-pb` (e.g. UnixFS v1.x) as it's just the size of the object + the size of it's links, but it becomes harder for `dag-cbor` (e.g. UnixFS v2) and other esoteric formats.

I would suggest leaving this alone until we land the pinning system refactor in #2771 - hopefully in `v0.46.0` as it's likely to disrupt this effort or vice versa.

**Comment by jakehemmerle** [comment]
It appears #2771 has been completed and merged. Is this ready to go?

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

I believe this should be resolved in Helia, if not, please let us know!
