### ISSUE TITLE
test trickle DAG importer

### ISSUE THREAD

**Issue by pgte** [ipfs/js-ipfs#2908]
* CLI `--trickle` option
* option on the add stream constructor

Depends on https://github.com/ipfs/go-ipfs/issues/3576 and https://github.com/ipfs/js-ipfs-unixfs-engine/issues/119

**Comment by achingbrain** [comment]
The interface tests could use a few tests around this, just ensuring the CIDs generated for some known inputs are the same should be enough.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

I believe this issue is related to the interop of js-ipfs and Kubo, and is irrelevant in Helia since Helia is not trying to be 100% compatible with the Kubo API.
