### ISSUE TITLE
IPFS-api issue

### ISSUE THREAD

**Issue by MaduraRaj** [ipfs/js-ipfs#2935]
Can anyone help me to solve this issue.
--------------------------
When I run 'npm install ipfs-api' This warn message pops up  
PS C:\Users\Madura\Desktop\image_uploader> npm install ipfs-api
npm WARN deprecated ipfs-api@26.1.2: ipfs-api has been renamed to ipfs-http-client, please update your package.json to get the latest version.
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Madura\Desktop\image_uploader\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Madura\Desktop\image_uploader\package.json'
npm WARN image_uploader No description
npm WARN image_uploader No repository field.
npm WARN image_uploader No README data
npm WARN image_uploader No license field.
---------------------------------------------------------------
After this when I try to 'npm run start' this issue comes
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Madura\Desktop\image_uploader\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Madura\Desktop\image_uploader\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Madura\AppData\Roaming\npm-cache\_logs\2020-03-21T19_07_28_043Z-debug.log

**Comment by achingbrain** [comment]
As the warning says, `ipfs-api` has been deprecated in favour of `ipfs-http-api`.  It's the same module, just with a different name.

That said I'm not sure what you are trying to do here.  If you're trying to run IPFS, the way to do it is:

```console
$ npm install -g ipfs
$ jsipfs daemon
```

Otherwise please see the [examples](https://github.com/ipfs/js-ipfs/tree/master/examples) folder for instructions on how to do common tasks, or take some of the tutorials on https://proto.school to learn how everything works.

Please open a thread on https://discuss.ipfs.io for further help using IPFS.
