### ISSUE TITLE
Docker images on Docker Hub are over a year old and broken

### ISSUE THREAD

**Issue by kalmi** [ipfs/js-ipfs#2952]
@victorb @daviddias The `latest` image on Docker Hub is over a year old, and is broken as described in #2018. Could you please have a look? It would be really nice to have.

I am working on a feature for go-ipfs, and it would be great to have a working latest Docker image as it would allow me quickly check current js-ipfs behaviours of the same feature.

**Comment by achingbrain** [comment]
Looks like docker pushes got taken out of the build process somewhere along the line - sorry about that, it should be back now.

You can get the current release in a docker image with `docker pull ipfs/js-ipfs:latest` but it's still broken due to https://github.com/ipfs/js-ipfs/issues/2019

But! If you instead use the RC of the next release with `docker pull ipfs/js-ipfs:next` that issue is fixed.  The RC will likely become the latest release tomorrow morning.

**Comment by kalmi** [comment]
Thank you, `next` works great
