### ISSUE TITLE
failed: Connection closed before receiving a handshake response and also index.js:752 GET https://node0.preload.ipfs.io/api/v0/refs?r=true&arg=QmTik5FwqQfkFapKPGK6TuADdJBdvopgkhgwbbyDTWskFe 502

### ISSUE THREAD

**Issue by kuabhish** [ipfs/js-ipfs#2981]
@alanshaw 
I am trying to make a dapp where i want to upload the hash of some file. But
I am getting this error 

I installed the ipfs with 
```
npm install -g ipfs
```
```   
 const filesAdded = await this.state.ipfs_node.add({
      path: this.state.file_path.name ,
      content:this.state.buffer,
    })
    console.log('--**--', filesAdded)
    this.setState({ipfsHash:filesAdded[0].hash})
    console.log('--', this.state.ipfsHash) //line 146
```
![Screenshot (371)](https://user-images.githubusercontent.com/11717742/79198962-e2c16f80-7e51-11ea-894f-884cdfd5697e.png)

**Comment by alanshaw** [comment]
Yes, your node is trying to connect to a public IPFS node but failing. There are two preload nodes and they may periodically be up and down. This is not necessarily a problem because your node will connect/use `node1.preload.ipfs.io` if `node0.preload.ipfs.io` is down.

We got a report that these were down around 2 hours ago when you posted this but it was back up shortly after. Please try again.

**Comment by kuabhish** [comment]
Hey @alanshaw 

I see the same error now also..

**Comment by alanshaw** [comment]
Great! Shall we consider this resolved?

**Comment by kuabhish** [comment]
Yes we can consider it.
But @alanshaw 
Is this error not important?

**Comment by jacobheun** [comment]
Closing this as the original issue is due to an outage on the preload nodes.

**Comment by RotonEvan** [comment]
The resilience of the preload nodes is still a problem. I'm facing a lot of 502 errors and cannot send or receive files quickly. Is there any third party solution to this?
