### ISSUE TITLE
ipfs.repo.gc() not working in ipfs-http-client 43.0.1

### ISSUE THREAD

**Issue by paul-xiao** [ipfs/js-ipfs#2985]
- **Version: ipfs-http-client 43.0.1**
- **Platform**:
- **Subsystem**:

#### Description:
i was using *ipfs-http-client 43.0.1* for a node app, trying to unpin file then run *ipfs.repo.gc()*
works in CLI : ipfs repo gc and *ipfs-http-client 41.0.1* , but fail in latest version (43.0.1)

guys, please have a look
am i doing it wrong ? 
how to make it work? 
thx

#### Steps to reproduce the error:
```bash
# unpin file
$ ipfs pin rm QmScC7nfe9KfqSQ6yP36zsiEzuNctrg6PTwGqEJ6p61oaR
unpinned QmScC7nfe9KfqSQ6yP36zsiEzuNctrg6PTwGqEJ6p61oaR

# get empty object
$ node gc.js
Object [AsyncGenerator] {}

# works in CLI
$ ipfs repo gc
removed QmScC7nfe9KfqSQ6yP36zsiEzuNctrg6PTwGqEJ6p61oaR
removed QmRdSHi3S6GNqPorBZqYdenyCUG2T517xEB4uBTPj8RQEf
removed QmfU1bRKHUKoeaB9GRETYaH9Yj4ZoGvit3QTTdogENtGDE
removed QmQCukevxvtz2rNyAzH9ANNPKdaEfhxxisQDA9X428GAJ1
```

```js
// gc.js
const config = require("../config");
const ipfsClient = require("ipfs-http-client");

const ipfs = ipfsClient({
  host: config.IPFS_HOST,
  port: config.IPFS_PORT,
  protocol: config.IPFS_OPTIONS.protocol,
});


const gc = async () => {
  try {
    let res = await ipfs.repo.gc()
    console.log(res)
  } catch (error) {
    console.log('err: '+ error.message)
  }
 
}

gc() // expect to have some results but get empty object

```

**Comment by achingbrain** [comment]
Since [`ipfs-http-client@42.0.0`](https://github.com/ipfs/js-ipfs-http-client/releases/tag/v42.0.0), `ipfs.repo.gc` returns an [AsyncIterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncIterator).  Please see the API docs: https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/REPO.md#repogc

To use it, you need to use the [`for await..of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of) statement:

```javascript
for await (const res of ipfs.repo.gc()) {
  console.log(res)
}
```

This is because the list of refs garbage collected can get very big and the old API would buffer these all up into an array before returning them.

If you want to simulate the old behaviour, you can use the [`it-all`](https://www.npmjs.com/package/it-all) module:

```javascript
const all = require('it-all')

const res = await all(ipfs.repo.gc())
console.log(res)
```

If you don't care about the result, you can use the [`it-drain`](https://www.npmjs.com/package/it-drain) module:

```javascript
const drain = require('it-drain')

await drain(ipfs.repo.gc())
```

**Comment by paul-xiao** [comment]
thanks a lot, this is exactly what i'm looking for
