### ISSUE TITLE
feature request: include reference to IPFS inside node instance

### ISSUE THREAD

**Issue by tabcat** [ipfs/js-ipfs#3053]
Hi, I'd like to be able to access classes like CID from just an 'instance' of ipfs made from the .create method on the IPFS factory object.
My use case is that I have a package that exports a class that takes an instance of ipfs as a parameter. I want to use the CID class included with the IPFS package instead of having to require it. Adding a reference to the IPFS factory object from the ipfs node instance object is one way to enable this.

**Comment by achingbrain** [comment]
> I want to use the CID class included with the IPFS package instead of having to require it.

This doesn't sound like a great idea, an instance should not have a reference to its factory.

Could you expand a little more on why you would do that?  Why not just require it?

```js
const {
  CID
} = require('ipfs')
```

**Comment by tabcat** [comment]
Pardon my ignorance on this but it seems like Class instances in javascript all have references to their factories via `.constructor`. Is it different since IPFS is not a Class or is it a good rule? Explicitly making a reference to the factory for the ipfs instance does sound useless, except for being able to access those bundled Classes.

> Could you expand a little more on why you would do that? It's bundled with IPFS as a top-level export, why not just require it?

I believe I just wished to inject CID with the IPFS instance. OrbitDB and my package that uses OrbitDB take an ipfs instance as a parameter to keep things simple for users. I was probably specifically looking to eliminate an older version of whats happening [here](https://github.com/cypsela/sailplane-node/blob/76e33c11018bacc4fc69649799c6e72abf272868/src/SharedFS.js#L90), which is actually not that bad because I have to create those preceding CID instances anyway.

**Comment by achingbrain** [comment]
> it seems like Class instances in javascript all have references to their factories via .constructor

They have a reference to their constructor, but a factory function might not be the constructor:

```js
class Foo {
  constructor () {

  }
}

function createFoo () {
  return new Foo()
}
```

IPFS is a class, but you get instances of it via the `create` factory method because it needs to do some async work before the node is ready to use (set up the repo, open ports, etc) which cannot be done in a constructor since they cannot be marked async.

> OrbitDB and my package that uses OrbitDB take an ipfs instance as a parameter
> I was probably specifically looking to eliminate an older version of whats happening here

In this project I would declare `ipfs` as a peer dependency and just require `CID` from it as per my previous comment above.

This also says to the user 'my project is compatible with this version of ipfs` and the user will get a warning if they don't declare a dep on ipfs at the right version.
