### ISSUE TITLE
`ipfs.dag` API docs missmatch implementation.

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3062]
So I have implemented `ipfs.dag` API as per documentation. E.g. [`ipfs.dag.get`](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/DAG.md#ipfsdaggetcid-path-options) per docs take `CID` instance.

However following tests exercise string and buffer inputs instead:

https://github.com/ipfs/js-ipfs/blob/5e0a18aa07c1852d2a7589899661761db50eeda9/packages/ipfs/test/core/dag.spec.js#L22-L32

We should update either docs or an implementation. I have also looked at [`/api/v0/dag/get`](https://docs.ipfs.io/reference/http/api/#api-v0-dag-get) but I am afraid it did not help me clarify here.

---

I am personally biased towards doing what API docs say, because otherwise in the shared worker use case we end up with double normalization / validation more specifically it would imply that:

1. Client needs to assess `cid` argument as either string, buffer, or CID.
2. Server piece would need to asses received `cid` input and decode it to one of those representations.
3. Server will pass decoded args to `ipfs.dag.get` which in turn will again asses `cid` argument.

It is also worth noting that if variadic `cid` is desired, it would make a lot more sense to analyze it in the main thread and error without messaging worker.

**Comment by achingbrain** [comment]
This is because the API previously specified strings, buffers and CIDs as arguments.  Going forward we only want to take CIDs, but the implementation still supports strings and buffers to avoid breaking existing code, though there needs to be a time limit on this.

New implementations of the core API can just support CIDs as per the API docs and skip the interface tests that test with non-CIDs.

**Comment by Gozala** [comment]
Cool, thanks for clarifying
