### ISSUE TITLE
Running OrbitDB tests in js-ipfs CI

### ISSUE THREAD

**Issue by aphelionz** [ipfs/js-ipfs#3202]
This is an idea that's been discussed between me and a few of the `js-ipfs` devs, as well as @autonome.

**Context**
[OrbitDB](https://orbitdb.org) is a popular library that builds on top of IPFS. It is a distributed database system that uses the IPFS DAG to store its operations log in a data structure called a CRDT. It interfaces with IPFS via either an in-process js-ipfs node or via the IPFS HTTP API via js-ipfs-http-client. Right now, the OrbitDB devs must pay "catch up" when a new js-ipfs release comes out, and as such we are not able to immediately use the latest and greatest features of IPFS.

**Proposal**
What I'd like to propose is to write a GitHub action that runs the battery of [OrbitDB tests](https://github.com/orbitdb/orbit-db/tree/master/test) on the pull requests this repository. Ideally, it would only respond to changes in code to either `packages/ipfs` and `packages/ipfs-http-client`.  

I don't expect that these checks would necessarily block any merges to code, since there may be changes required in OrbitDB's code itself, but it will be extremely useful to learn about such things far sooner, so that the OrbitDB devs can move much faster. In a perfect world, we could release OrbitDB versions in lock-step with IPFS versions.

**Comment by achingbrain** [comment]
We already have something like this - see the `external - orbit-db` job in [.travis.yml](https://github.com/ipfs/js-ipfs/blob/master/.travis.yml#L200-L205).

The external project tests run after an RC has been published, which happens with every commit to master.  They work by checking out the target repo & running their tests, if they pass, it switches any `ipfs` or `ipfs-http-client` dependencies for the latest RC and runs the tests again.

Though:

1. They've been allowed to fail since the async/await API refactor in `v0.41.0` while people make the upgrade, I just need to go through them all and re-enable the ones who have upgraded
2. It looks like you pulled `ipfs` out of the dev deps [a while ago](https://github.com/orbitdb/orbit-db/commit/572029bbe72ca5b7ef78df35449639f0716c7127#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L49) so this won't work any more as is

All you need to do is add `ipfs` back to the dev deps of orbit-db or create another repo that runs the orbit-db tests with `ipfs` as a dependency and I can re-enable this.

**Comment by tabcat** [comment]
Hello I'm here to help get this ball rolling again. I've made branches for [orbit-db](https://github.com/tabcat/orbit-db/tree/fix/ipfs-tests) and [ipfs-log](https://github.com/tabcat/ipfs-log/tree/fix/ipfs-tests) that use the newer version of our test utility and have the ipfs packages as local dev dependencies.

What is the next step we need to handle? Getting the changes merged into their respective master branches?

**Comment by tabcat** [comment]
@achingbrain @lidel
