### ISSUE TITLE
Ipfs-http-client throws an error when running jest/jsdom unit tests

### ISSUE THREAD

**Issue by lukaw3d** [ipfs/js-ipfs#3238]
- **Version**:

ipfs-http-client@46.0.0

- **Platform**:

```
node@12.18.3
──┬ jest@26.4.1
  └─┬ @jest/core@26.4.1
    └─┬ jest-config@26.4.1
      └─┬ jest-environment-jsdom@26.3.0
        └── jsdom@16.4.0 
```

- **Subsystem**:

#### Severity:

Medium

#### Description:

- What you did:
  Updated a dependency and tried to run unit tests with default jest configuration. Subdependency ipfs-http-client@40.1.0 updated to ipfs-http-client@46.0.0 and was imported `require('ipfs-http-client')` but not instantiated in tests.

  `jest --env=node` works as a workaround, if you don't need DOM

- What happened:
  Tests crash on initialization. Global `XMLHttpRequest` is defined (so it uses `ipfs-utils/src/http/fetch-browser.js`), but global `Request` isn't (throws `ReferenceError`).

- What you expected to happen
  Expected ipfs-http-client to continue working with jest/jsdom

#### Steps to reproduce the error:

```sh
newfolder
npm init -y
npm i ipfs-http-client@46.0.0
npm i jest
echo "require('ipfs-http-client'); test('a', () => {});" > a.test.js

npx jest   # [--env=jsdom] 
#> ReferenceError: Request is not defined
#  ipfs-utils/src/http/fetch-browser.js:95

npx jest --env=node
#> Success
```

**Comment by mitjat** [comment]
I'm also affected by this.
Stack trace when running the repro:
```
    ReferenceError: Request is not defined
      at Object.<anonymous> (node_modules/ipfs-utils/src/http/fetch.browser.js:95:19)
      at Object.<anonymous> (node_modules/ipfs-utils/src/http/fetch.js:6:20)
      at Object.<anonymous> (node_modules/ipfs-utils/src/http.js:4:37)
      at Object.<anonymous> (node_modules/ipfs-utils/src/files/url-source.js:3:14)
      at Object.<anonymous> (node_modules/ipfs-http-client/src/index.js:10:19)
```

The third line (`node_modules/ipfs-utils/src/http.js:4:37`) points to https://github.com/ipfs/js-ipfs-utils/blame/master/src/http.js#L4, which has recently (6 days ago) been modified to no longer use `fetch.js` (= the second line from the stack trace above).

So it looks likely that the problem was introduced by https://github.com/ipfs/js-ipfs-utils/pull/54 and has since been reverted/fixed in `ipfs-utils`. So hopefully, `ipfs-http-client` just needs to use v3.0 of `ipfs-utils`: https://github.com/ipfs/js-ipfs-utils/releases

**Comment by lukaw3d** [comment]
Ah, it works in ipfs-http-client@next (46.0.0-rc.2)
