### ISSUE TITLE
Remove use of `ipfs.object.*` from test suite

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#3301]
If we ever want to deprecate `ipfs.object.*` we should not rely on it in our interface tests, because then new implementations have to implement "soon"-to-be-deprecated-APIs which makes no sense.

We should remove all uses of `ipfs.object.*` and replace it with `ipfs.dag.*` or whatever makes sense.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue won't be fixed in js-ipfs but there is replacement functionality available in Helia that should work much better.
