### ISSUE TITLE
ipfs.bitswap.unwant takes CID|CID[] in core but CID|string in http-client

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3335]
At the moment `ipfs.bitswap.unwant` API is incompatible between ipfs-core and ipfs-http-client. Former accepts array of CIDs (but also strings, even though it's not documented)

https://github.com/ipfs/js-ipfs/blob/4b8021d389ac01f191d4fe87beead10088e53297/packages/ipfs-core/src/components/bitswap/unwant.js#L26-L34

 While later assumes single `CID` or string:

https://github.com/ipfs/js-ipfs/blob/4b8021d389ac01f191d4fe87beead10088e53297/packages/ipfs-http-client/src/bitswap/unwant.js#L16

**Comment by achingbrain** [comment]
In the short term the http client should be brought in line with [the docs](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/BITSWAP.md#parameters-2).

In the long term we should probably remove this method from the core-api, it's not supported by go-IPFS or exposed by the http API there so it only works with js-IPFS and as such seems like some unnecessary API surface area.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue won't be fixed in js-ipfs but there is replacement functionality available in Helia that should work much better.
