### ISSUE TITLE
Implement and document ipfs.files.rm --force

### ISSUE THREAD

**Issue by olizilla** [ipfs/js-ipfs#3355]
go-ipfs supports a `--force` flag on `ipfs files rm` which is useful in scripts that want to use the mfs and reset a dir as the first step, regardless of if it exists or not.

- https://docs.ipfs.io/reference/http/api/#api-v0-files-rm
- https://docs.ipfs.io/reference/cli/#ipfs-files-rm

I can pass `force: true` via the `ipfs-http-client` and if i'm talking to a go-ipfs node it works, but it's not documented in https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#ipfsfilesrmpaths-options

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue won't be fixed in js-ipfs but there is replacement functionality available in kubo-rpc-client that should work much better.
