### ISSUE TITLE
Mixed Content: The page at '<URL>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint

### ISSUE THREAD

**Issue by hunterInt** [ipfs/js-ipfs#3375]
- **Version**:
0.50.2

- **Platform**:
Linux ubuntu 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

#### Severity:

  Medium - A non-essential functionality does not work, performance issues, etc.

#### Description:
My console is filled with these errors (already 400+ in just under a minute of page load):

![cap](https://user-images.githubusercontent.com/14793417/98451349-fb50ea00-2101-11eb-82c4-a387bb081583.png)

Is there a way to either prevent my `HTTPS` page from attempting to load non-ssl connections or suppress these errors? 

#### Steps to reproduce the error:
```
await IPFS.create();

for await (const chunk of ipfsNode.cat(CID)) {
	chunks.push(chunk);
}
```

**Comment by jacobheun** [comment]
The underlying issue is that libp2p needs to be more restrictive of its websocket dials, especially in browsers. This is being tracked at https://github.com/libp2p/js-libp2p/issues/796.

**Comment by achingbrain** [comment]
This should be fixed by https://github.com/libp2p/js-libp2p-websockets/pull/116 in the near future.

**Comment by SgtPooki** [comment]
js-IPFS is being deprecated, the replacement is [Helia](https://github.com/ipfs/helia). It's a modern, lightweight, and composable take on what IPFS can be in JS and is where the team's energy will be focussed moving forwards.

To help you upgrade your app to use Helia please see the following resources:

- [Migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS)
- [FAQ](https://github.com/ipfs/helia/wiki/%E2%9D%93-FAQ)
- [Hello Helia talk](https://www.youtube.com/watch?v=T_FlhkLSgH8)
- [The State of IPFS in JS](https://blog.ipfs.tech/state-of-ipfs-in-js/)

This issue was fixed in libp2p by https://github.com/libp2p/js-libp2p-websockets/pull/116, and the latest libp2p is included in helia
