### ISSUE TITLE
API simplification: remove `cid` argument to `ipfs.dag.put`

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#3380]
I'm not sure why this is an option, the whole point of `ipfs.dag.put` is to put some data and get a CID back.  If you have the CID, you've already put the data so what are you doing here?  It's also not supported by go-IPFS so it's not a hard requirement.

Suggestion: remove the `cid` option from `ipfs.dag.put`

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue won't be fixed in js-ipfs but there is replacement functionality available in Helia that should work much better.
