### ISSUE TITLE
API simplification: remove `ipfs.bootstrap.*` from Core API

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#3381]
You can do all of these bootstrap list manipulations with the `ipfs.config.*` API, except, I think, resetting the bootstrap list to the defaults.

Suggestion: remove `ipfs.bootstrap.*` from the Core API (n.b it would remain in the CLI and HTTP APIs for go-IPFS compatibility)

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue won't be fixed in js-ipfs but there is replacement functionality available in Helia that should work much better.
