### ISSUE TITLE
Streamlining IPFS Config 

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3390]
https://github.com/ipfs/js-ipfs/pull/3365 spawned discussions around config. I think deserves a separate conversation and possibly pull request based on consensus.  

Right now there are various assumptions made about the config across the code base e.g.

- Some code paths assume that config will have certain properties e.g. `Addresses` or `Discovery`.
- Other code paths assume that it my not have anything at  all.
- Some other code paths assume that merging incomplete config with some other (possibly invalid / incomplete config e.g read from file) will result in complete config.

All this makes it very difficult to encode invariants in type checker and uphold them as well. I would like to propose isolating the config parsing, merging access with defaults etc... into separate module that deals with all this so all the code paths can be be free of those concerns and be valid.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
