### ISSUE TITLE
Make unecessarily async functions sync

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3392]
We should remove artificially induced asyncness as per https://github.com/ipfs/js-ipfs/pull/3365/files/fa7c2c13c43bab922052104fe8aff863d9725e9b?file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.ts#r516573074

**Comment by Gozala** [comment]
One thing to consider during this change is that with async functions it is guaranteed that they do not throw but always return a promise that may fail. sync functions could both throw and return promise that fails.

**Comment by achingbrain** [comment]
Yes, this is something we've talked about a lot and has previously been identified as a real-world performance bottleneck.

Historically we've marked API methods async in order to clearly signal to the caller that a promise will be returned, even if we're just calling through to another module that does the actual async work.

With the expanded type def support this should no longer be necessary so we should be safe to start removing the `// eslint-disable-line require-await` comments and pulling out the artificial async.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
