### ISSUE TITLE
Tests for some API functions are not obvious

### ISSUE THREAD

**Issue by haadcode** [ipfs/js-ipfs#352]
I find it confusing how the tests are setup and located.

Trying to look for tests in https://github.com/ipfs/js-ipfs/blob/master/test/core/both/test-files.js makes me think we don't have tests for `ipfs.files.cat`. Looking at it more closely, I can see the tests are in `interface-ipfs-core` and I need go find that repository on GH. So I find it, go to the `test` directory and see this https://github.com/ipfs/interface-ipfs-core/tree/master/test (empty directory). Then browsing through the repository, I finally understand that the tests are in `src` https://github.com/ipfs/interface-ipfs-core/blob/master/src/files.js.

This is hugely unintuitive and takes a lot of knowledge to be able to check the tests (eg. for reference implementation, how to use the functions, etc.). One is required to understand that the tests are in a separate repository, then to realize to look under `src`.

**Comment by diasdavid** [comment]
We've added: https://github.com/ipfs/js-ipfs#api

Any proposals on how to make it more dev friendly?

**Comment by diasdavid** [comment]
We've improved a lot since this issue was last opened, namely:

- Development instructions with commands to run tests: https://github.com/ipfs/js-ipfs#run-tests
- API documentation pointers to interface-ipfs-core https://github.com/ipfs/js-ipfs#api
- Usage examples https://github.com/ipfs/js-ipfs#usage
- Tests are organized by which area they are testing https://github.com/ipfs/js-ipfs/tree/master/test

Let me know if you think of other ways we can make this better (or even with a PR :)), otherwise closing this issue until there is other actionable actions :) Thank you.
