### ISSUE TITLE
Enable WebRTC by default in the browser?

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs#3541]
We could enable a `/dns4/wrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star` address by default for the browser config.

We could also enable transport manager fault tolerance for the browser libp2p config so it doesn't crash the node if `/dns4/wrtc-star.discovery.libp2p.io` is unavailable.

Pro: When it works, it works:tm:
Con: When it doesn't, the user will not know why it doesn't work

cc @vasco-santos @lidel

**Comment by lidel** [comment]
> reposting from private channels (cc @autonome @gozala)

IIf we enable this, most of js-ipfs nodes will use the default (implicit) signaling server.
This is a problem IMO, because if that service goes down, js-ipfs will fail to start.

We could mitigate that by [configuring transport manager](https://github.com/libp2p/js-libp2p/blob/0a6bc0d1013dfd80ab600e8f74c1544b433ece29/doc/CONFIGURATION.md#configuring-transport-manager) to not fail js-ipfs start process if signaling server is down:

```
  transportManager: {
    faultTolerance: FaultTolerance.NO_FATAL
  }
```
----

I'm :+1: for doing this in browser bundle + **displaying console log warning** when default webrtc-star  is used with link to self-hosting instructions at:  https://github.com/libp2p/js-libp2p-webrtc-star/blob/master/DEPLOYMENT.md

**Comment by autonome** [comment]
+1 to:

* "Just Works™️" most of the time
* with some centralization cost (for now)
* and a warning in console pointing to docs, so there's a thread to pull on in the cases where it doesn't work

Potential follow-ups:

* Expand the Public Gateway Checker page/repo to cover these types of nodes
* Work w/ collab partners to run these servers, add to above list
* Have js-ipfs include a set of vetted community servers, rotate on node start, or other heuristics (eg RTT)

**Comment by achingbrain** [comment]
Completely pull ideas out of thin air here, but it would be great if the signalling servers could themselves do some sort of cross-server discovery - use libp2p pubsub to publish handshake offers or peer lists and then relay traffic between browser nodes until they set their own connections up?

Then we could round-robin incoming connections between our own hosted nodes to make it a bit more scalable and even federate with other signalling servers hosted elsewhere?

**Comment by vasco-santos** [comment]
>  use libp2p pubsub to publish handshake offers or peer lists and then relay traffic between browser nodes until they set their own connections up?

The signal server is not a libp2p node, which complicates things here a bit.

We have been talking about having the distributed signalling implemented in the relays and I think the time needed to update the star servers properly would be better used to do this on top of the libp2p relay. This has been discussed in the [past](https://github.com/libp2p/js-libp2p/issues/385#issuecomment-514300699) but we never had progress with the spec for this.

**Comment by achingbrain** [comment]
> The signal server is not a libp2p node

I know, but it could be.  That would have been an ace hack week project.  Maybe next time..

**Comment by Gozala** [comment]
> but it would be great if the signalling servers could themselves do some sort of cross-server discovery - use libp2p pubsub to publish handshake offers or peer lists and then relay traffic between browser nodes until they set their own connections up?

Me and @hugomrdias created a pitch towards this end https://github.com/protocol/web3-dev-team/pull/43

**Comment by Gozala** [comment]
One other thing to consider here that there is no WebRTC in the worker threads, so browser config would have to check if `WebRTC` is available in the context before enabling it.

**Comment by Gozala** [comment]
> Given that we already run two nodes which gives us basic redundancy + are able to keep things working even when centralized signaling is down, I am supportive for enabling WebRTC by default **but only if we print annoying error to the browser console** like this:

I think using separate signaling servers has downside of fragmenting a network, maybe instead of suggesting to switch to own signaling we should instead incentivize to adding more signaling nodes instead ? Although I'm not sure if multiple signaling nodes would just split network randomly or will allow to create bridges across them, we would want a later.

Long term I think we should really think about how to enable teams to expand the infrastructure without fragmenting the network by product. I think we should aspire to empowering users to choose a provider as opposed to dev teams prescribing it.

**Comment by phillmac** [comment]
It seems like the existing servers are very hit and miss, they regularly cause 
```
Uncaught (in promise) AggregateError: 

    Error: peer is not available
```
Whatever we do we need to prioritise stability.
I've had this error on private servers too, so not sure if it's particularly related to the public servers.
Just thought I'd put in my 2¢ to explain how difficult it is to get js-ipfs configured properly, the flakiness makes it exceptionally hard to diagnose what's even the issue here.
See https://github.com/orbitdb/orbit-db/issues/873#issuecomment-812878896

**Comment by SgtPooki** [comment]
related: https://github.com/libp2p/js-libp2p/issues/1478

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

I believe this is done now thanks to https://github.com/ipfs/helia/blob/main/packages/helia/src/utils/libp2p.browser.ts
