### ISSUE TITLE
Regression in ipfs.ls in HTTP client

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs#3566]
Following change seems to have introduced a regression:
https://github.com/ipfs/js-ipfs/commit/f243dd1c37fcb9786d77d129cd9b238457d18a15#

Specifically following code:

```ts
const emptyDir = new CID('QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn')
for await (cont entry of ipfs.ls(emptyDir)) {
  console.log(entry)
}
```

Would have logged nothing before this change and now logs:

```js
{
  "path": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "cid": emptyDir,
  "type": "unknown",
  "depth": 1
}
``` 

That is also incompatible with embedded ipfs implementation.

**Comment by Gozala** [comment]
I'll submit a fix after I'm done with ipfs-shipyard/ipfs-webui#1655

**Comment by achingbrain** [comment]
I think the bug is with `ipfs-core` here - if I add the following test to `interface-ipfs-core/src/ls.js`:

```js
it('should ls an empty directory', async () => {
  const emptyDir = new CID('QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn')
  const output = await all(ipfs.ls(emptyDir))

  expect(output).to.have.lengthOf(1)
  expect(output[0]).to.have.property('path', emptyDir.toString())
  expect(output[0]).to.have.property('depth', 1)
  expect(output[0]).to.have.property('type', 'unknown')
})
```

it passes against go-ipfs and js-ipfs over http but fails against ipfs-core.

The `type: 'unknown'` thing is a bit weird, it should really be `'dir'`, but you don't get much information back from the HTTP API, only the hash and an empty array for the links.

**Comment by achingbrain** [comment]
Actually, thinking about this more, we generally try to imitate what you'd get on the command line.  If I `ls` an empty directory I get nothing back, but if I `ls` a single file, I get the file back, so this is probably a regression in the http clients as in the OP.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue won't be fixed in js-ipfs but there is replacement functionality available in kubo-rpc-client that should work much better.
