### ISSUE TITLE
bug: use correct version IPFS version number

### ISSUE THREAD

**Issue by lidel** [ipfs/js-ipfs#3622]
> The version number that `ipfs.version()` outputs should be the one of the release.
> 
> Right now it is the version of the `ipfs-core` package.

Potential solution (TBD):

- read the latest github release / NPM version of `ipfs` package at the build time  and hardcode it in `ipfs-core`

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
