### ISSUE TITLE
[Types] IPFS.create() options uses Libp2pConfig instead of Libp2pOptions

### ISSUE THREAD

**Issue by rvagg** [ipfs/js-ipfs#3640]
Ref: https://github.com/ceramicnetwork/js-ceramic/pull/1194#discussion_r606629404

https://github.com/ipfs/js-ipfs/blob/63b11e5ac9d0b36d89ec23966e4523721878a7c0/packages/ipfs-core/src/types.d.ts#L8

Sooo .. it looks like what's going on here is that ipfs-core is pulling in `Libp2pConfig` when it should be pulling in `Libp2pOptions` because `Libp2pConfig` is used for the `config` property inside `Libp2pOptions`. So in https://github.com/ceramicnetwork/js-ceramic/pull/1194 I was having to pull up the elements in the `libp2p.config` object into `libp2p` to satisfy this condition. I think this should just be:

```js
import type { Libp2pOptions } from 'libp2p'
```

**Comment by vasco-santos** [comment]
This should be the same as https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core/src/components/libp2p.js#L16 .

**Comment by achingbrain** [comment]
Ah, annoying - that type doesn't actually look like it's used anywhere in the file. I wish our linter would pick that up.

**Comment by vasco-santos** [comment]
https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core/src/components/libp2p.js#L70 this function should return it, right?

**Comment by achingbrain** [comment]
We'd need to add a `/** @type {Options} */` to https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core/src/components/libp2p.js#L164 otherwise it'll infer the return type instead of using the one defined in the `@typedef`.

That'd be fine initially but if we removed a property or something it'd just update the inferred return type rather than erroring on the change.
