### ISSUE TITLE
React (and Vue) IPFS Cannot Compile

### ISSUE THREAD

**Issue by logasja** [ipfs/js-ipfs#3690]
This is in reference to this issue on the forum.
https://discuss.ipfs.io/t/react-ipfs-cannot-compile/11266

- **Version**:

ipfs-core: 0.6.1

- **Platform**:

Linux

#### Severity:

High

#### Description:

I have been looking into how to fix this for a while and it seems like the linked discussion from three days ago is the only mention of it. Basically, my TypeScript Vue CLI application will not build because of some webpack issue. I have since downgraded to ipfs-core 0.5.4 and everything compiles correctly.

#### Steps to reproduce the error:

Use @vue/cli to make a Vue 3 typescript project, install and import IPFS, attempt to spawn a node, compile.

**Comment by BasBastiaansen** [comment]
Same for Angular. It doesn't want to compile. I have made a stackoverflow question about it a few days ago: [https://stackoverflow.com/questions/67431408/ipfs-npm-package-with-angular-not-working](https://stackoverflow.com/questions/67431408/ipfs-npm-package-with-angular-not-working)

**Comment by negamaxi** [comment]
Same for CRA:

![Снимок экрана от 2021-05-23 20-02-36](https://user-images.githubusercontent.com/16529171/119269747-f10bbe80-bc01-11eb-8273-a83acbaa997f.png)

Just updated to ipfs v0.55.1

**Comment by achingbrain** [comment]
The problem here is that the babel config react/angular/vue are using does not support optional chaining, which is a shame as it's actually supported in all modern browsers and current/lts node.

I've just published an rc of ipfs without this modern syntax - could you please try again with the `next` version and let me know if it resolves the issue?  E.g. `npm install ipfs-core@next`.

If it works I'll publish a patch release with the fix.

**Comment by logasja** [comment]
That works for me in Vue and React

**Comment by achingbrain** [comment]
The fix has been released as `ipfs@0.55.2` and `ipfs-core@0.7.0` so please set your dependency versions to that.
