### ISSUE TITLE
Export all types from "ipfs-core-types" root.

### ISSUE THREAD

**Issue by ocknamo** [ipfs/js-ipfs#3713]
- **Version**:

ipfs-core: 0.7.1

- **Platform**:

Ubuntu 20.04.2 LTS 
64-bit

- **Subsystem**:

ipfs-core-types: 0.5.1

#### Severity:

Low

#### Description:

It would be useful if all types were exported from the root of "ipfs-core-types".

Pros

- Application build do not fail when change the place of type definition file.
- Easy to find types via support of editor. (I wrote this issue because I had a hard time finding the "ImportCandidateStream".)
- Import statement will be reduced.

Cons

I have no idea.

#### example

```
// ipfs-core-types/src/index.d.ts
...

export * from './utils'
export * from './root'
export * from './bitswap'
export * from './block'
...

```

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
