### ISSUE TITLE
Progress callback when using addAll

### ISSUE THREAD

**Issue by SoftCreatR** [ipfs/js-ipfs#3870]
I don't know, if this works as designed, but I can't find a way to track the overall upload progress when using addAll / upload multiple files at once. This works for a single file:

```js
const uploadProgress = len => {
  const percentage = Math.round((len / totalfileSize) * 100)
  
  document.getElementById("progressBar").style.width = `${percentage}%`
}
```

Pretty straight forward and functional as expected. It just gets complicated when uploading multiple files at once, updating a single progress bar, especially because if a file has been uploaded, the percentage starts from 0.

Maybe, this isn't an issue at all and I'm just thinking too complicated?

**Comment by achingbrain** [comment]
This is by design as you're adding a stream of bytes which doesn't give any indication of how long the stream is.

The signature for the progress callback is [`(bytes, path) => {}`](https://github.com/ipfs/js-ipfs/blob/b2f0ef4ecbde6deb3b054c4469c1674c0fde51c3/packages/ipfs-core-types/src/root.ts#L151), so if you can find out the length of the input another way (e.g. querying the filesystem in node or blob length in the browser etc) you can calculate it yourself as you've found.

If you are importing multiple files you can use the `path` arg to work out which file you're receiving progress notifications about.

**Comment by SoftCreatR** [comment]
@achingbrain Thank you for pointing to the right direction. I wasn't aware of the `path` parameter. This works for me:

```js
const progressSizes = {}
const uploadProgress = (len, path) => {
  progressSizes[path] = bytes
  const percentage = Math.round(((Object.values(progressSizes).reduce((a, b) => a + b)) / totalfileSize) * 100)
  
  document.getElementById("progressBar").style.width = `${percentage}%`
}
```
