### ISSUE TITLE
ipfs-http-client upload folder not work

### ISSUE THREAD

**Issue by ziboilihua** [ipfs/js-ipfs#3873]
- **Version**:
{
  version: '0.9.1',
  commit: 'dc2715a',
  repo: '11',
  system: 'amd64/linux',
  golang: 'go1.15.2'
}

- **Platform**:
Darwin localhost 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

#### Severity:
High

#### Description:
ipfs-http-client will throw this error when add Folder use globSource, I use it in nodejs project at local
```js
AbortError: The user aborted a request.
```

#### Steps to reproduce the error:

```js
const { create, globSource } = require('ipfs-http-client')

async function uploadFile() {
    const ipfs = create('http://localhost:15001');
    const file = await ipfs.add(globSource('./docs', { recursive: true }))
    console.log(JSON.stringify(file))
}

uploadFile();
```

**Comment by achingbrain** [comment]
`ipfs.add` only accepts single items to add to IPFS.  `globSource` returns multiple items which is why you're seeing an error, though granted the error message could be more descriptive.

Please change the invocation to:

```js
const file = await ipfs.addAll(globSource('./docs', { recursive: true }))
```

Also note the globSource API changed in the `ipfs-http-client@53.x.x` release so now it would be:

```js
const file = await ipfs.addAll(globSource('.', 'docs/**/*'))

// or if you prefer:

const file = await ipfs.addAll(globSource('./docs', '**/*'), {
  wrapWithDirectory: true
})
```
