### ISSUE TITLE
js-ipfs and custom codec: can not retrieve a CID

### ISSUE THREAD

**Issue by ukstv** [ipfs/js-ipfs#3941]
Hello, IPFS team. We are currently upgrading to the latest versions of ipfs-related packages. We found ipfs-core does not retrieve a CID that uses custom codec [dag-jose].

Here is a repository that reproduces the issue: https://github.com/stephhuynh18/Help

It creates two in-process ipfs instances, on different ports. It swarm-connects them together. We could see them connected together on `ipfs.swarm.peers`. First, we put usual JSON-like data on one IPFS node, and retrieve it on another. It works all right, as expected. Then, we put dag-jose data on one IPFS node [we retrieve the data from this node all right], and try to retrieve it on another. This retrieval just hangs indefinitely.

We thought it could be something with our codec. We could confirm all the encoding/decoding operations on the first IPFS node, where we originally put the data. On retrieval node, to our surprise, `decode` function of our `dag-jose` codec was not invoked at all.

If downgraded to ipfs-core v0.7, and wrapping codec with `convert` from `blockcodec-to-ipld-format`, it works.

Please, pals, could you direct us to what could go wrong?

CC @stephhuynh18

**Comment by oed** [comment]
@achingbrain @rvagg any ideas on this?

**Comment by rvagg** [comment]
From what I can tell, everything in the codec path is correct here, including down into ipfs-core and it _should_ work, so maybe this is a network/p2p problem (that I don't have a whole lot of insight into tbh).

What happens if you switch out the retrieval to `ipfs.block.get(cid)`, does it change anything?

**Comment by ukstv** [comment]
ipfs2 can not retrieve the block either.

**Comment by ukstv** [comment]
It feels, like we found a bug in bitswap code.

A block with [dag-jose](https://github.com/multiformats/multicodec/blob/master/table.csv#L53) codec (`0x85`), it seems, can not be [deserialized](https://github.com/ipfs/js-ipfs-bitswap/blob/76e183924ffae38f0a5c1202a9f250e1075ab3ca/src/types/message/index.js#L285) properly. It treats codec id `0x85` as varint component.

[Serialization](https://github.com/ipfs/js-ipfs-bitswap/blob/76e183924ffae38f0a5c1202a9f250e1075ab3ca/src/types/message/index.js#L179) part: combine
- cid version `1` (decimal)
- with codec `133` (decimal) (=`0x85` hex = `dag-jose` according to multicodec table)
- with multihash `sha2-256` (=`20` decimal=`0x12` according to multicodec table)
- the last component `32` is sha2-256 digest length in bytes somehow
So, serialized prefix is `Uint8Array(4) [ 1, 133, 18, 32 ]`


When doing [deserialization](https://github.com/ipfs/js-ipfs-bitswap/blob/76e183924ffae38f0a5c1202a9f250e1075ab3ca/src/types/message/index.js#L285), `varint-decode` package is used. It seems, that codec id `133` decimal = `0x85` confuses it. Deserialized prefix results in
- cid version `1` (decimal) - ok,
- codec `2309` (decimal) - WRONG,
- multihash `32` (decimal) - WRONG.

So, custom codec with number `0x85` = `133` decimal prevents a block from being transferred.

Code to reproduce serialization-deserialization behavior: https://github.com/ukstv/bitswap-serde-maybe-broken

And, this is what we see in our `Help` repository. You could replace contents of `node_modules/ipfs-bitswap/esm/src/types/message/index.js` with `https://gist.github.com/ukstv/67e4d8e8e493681a677f3ae4fdeca63c` and see how it corresponds to the isolated replication.

**Comment by ukstv** [comment]
@rvagg @achingbrain I can create an issue on bitswap side, if it helps to organise things.

**Comment by achingbrain** [comment]
This should be fixed by ipfs/js-ipfs-bitswap#383 - please remove your `node_modules` folder and reinstall and you should get `bitswap@7.0.1` which has a fix for the issue.

The problem, as you found above, was that we were encoding the CID prefixes incorrectly.  This operation used to be done by the `cids` module but it didn't make it across to `multiformats/cid` and a bug crept into `bitswap` during the switch-over. 

The prefix should be a buffer full of varints, but we were just sending a concatenated array of numbers so the decode was correct but encoding was broken.

**Comment by ukstv** [comment]
Great. Thank you! Going to test. Will post here the results.

**Comment by ukstv** [comment]
It works!!!!!!! Thank you @achingbrain

Closing now.
