### ISSUE TITLE
Not able to build the project

### ISSUE THREAD

**Issue by Kannas24** [ipfs/js-ipfs#3948]
**Error:** node_modules/ipfs-core-types/types/src/utils.d.ts:78:21 - error TS2456: Type alias 'ToJSON' circularly references itself.

`export declare type ToJSON = null | string | number | boolean | ToJSON[] | ({
    toJSON?: () => ToJSON;
} & {
    [key: string]: ToJSON;
});`

Node version: 12.13.0 and 16.13.0
Typescript version: 3.9.6 and 4.5.2

**Comment by achingbrain** [comment]
I don't think that type is even used anywhere.  What happens if you remove it from `node_modules/ipfs-core-types/types/src/utils.d.ts`?

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
