### ISSUE TITLE
Documentation and code discrepancy for ipfs.block.put

### ISSUE THREAD

**Issue by ukstv** [ipfs/js-ipfs#3960]
Documentation on `ipfs.block.put` [here](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/BLOCK.md#options-1) states that one can pass `cid` option.

[Code](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core/src/components/block/put.js#L30) though have no use of that option.

Should there be a PR to adjust the code or the docs?

**Comment by ukstv** [comment]
Pals, @achingbrain  may I ask for clarification rather than an actual change here? I see that `cid` option was removed as part of upgrade to use `multiformats`. Was it intentional, or a mistake? I mean, if we propose a PR that takes back the option, would it be all right with you?

**Comment by achingbrain** [comment]
It wasn't a mistake, the problem is the option doesn't make much sense - you pass in a buffer and say "store it under this CID" but it might not be the right block for that CID.

You could hash the block and find out, but then you've just recreated the CID so there's no performance gain or anything, in fact you've made it worse because you'll always hash the block twice - once to create the CID to pass to `block.put` and then again to verify that the correct CID was passed to `block.put`.

Better just to remove the option.
