### ISSUE TITLE
globalThis Error in Safari

### ISSUE THREAD

**Issue by amrap030** [ipfs/js-ipfs#3971]
- **Version**: "ipfs-core": "^0.12.2"

- **Platform**: Darwin amrap030-mbp-37305.fritz.box 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

#### Description:

When using `ipfs-core` in a Vue 3 Application, everything works fine in Chrome and Firefox. However, in Safari Version 12.0 (14606.1.36.1.9) I am getting the following error: `ReferenceError: Can't find variable: globalThis` and the UI is not loading anymore.

#### Steps to reproduce the error:

You can reproduce the error by using the following repository: https://github.com/amrap030/ipfs-safari

You just need to run `npm install` and then `npm run serve`

You should get the error when running the current state of the repository. After removing everything related to ipfs in [this file](https://github.com/amrap030/ipfs-safari/blob/199d8c90b6ebc65249dffb65c5a2aa8e793c8877/src/services/index.ts#L3-L11), the application ui loads as expected and the error is gone.

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
