### ISSUE TITLE
Allow to filter out private ips

### ISSUE THREAD

**Issue by dapplion** [ipfs/js-ipfs#3982]
Lodestar is using libp2p-js for p2p networking in deployed nodes at Hetzner.

We got an abuse message from Hetzner identical to this one https://github.com/MinaProtocol/mina/issues/7053

I've configured ufw to block traffic to private IPs, but libp2p may consider supporting this feature natively as implemented in this libp2p fork https://github.com/MinaProtocol/mina/pull/7188

**Comment by achingbrain** [comment]
I think you should just be able to add private swarm addresses to the `NoAnnounce` list? - https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core-config/src/config.js#L9

**Comment by dapplion** [comment]
> It looks like [MinaProtocol/mina#7188](https://github.com/MinaProtocol/mina/pull/7188) just removes private addresses from the list a node announces to peers - I think you can do the same thing by just adding your private swarm addresses to the `NoAnnounce` list? - https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core-config/src/config.js#L9

The issue is my libp2p instance trying to dial other peers at private addresses.

**Comment by achingbrain** [comment]
You could [configure an address sorter](https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md#configuring-dialing) that removes addresses you don't want to dial?

Otherwise you could try out the [connection gater PR](https://github.com/libp2p/js-libp2p/pull/987/files) as it will give you a bit more fine-grained control.

One thing springs to mind though, how can you know in advance that a given address is not valid and should not be dialled?

I suppose you could filter out private IP ranges that are not in the same range/subnet as your own private addresses which would still let you dial peers on your LAN, but what if a peer on a remote network had the same range/subnet as you?

**Comment by dapplion** [comment]
> You could configure an address sorter that removes addresses you don't want to dial?

This should work!

> how can you know in advance that a given address is not valid and should not be dialled?

The cloud provider we are using will close our servers if you try to contact a set of IP ranges defined in their docs :sweat_smile:

**Comment by dapplion** [comment]
@achingbrain For performance concerns, does libp2p run the address sorter strictly once per peer?

**Comment by achingbrain** [comment]
It sorts the addresses once [when you create a dial target](https://github.com/libp2p/js-libp2p/blob/master/src/dialer/index.js#L199) - e.g when you dial a peer.

**Comment by lidel** [comment]
Seems to be resolved/answered
