### ISSUE TITLE
refactor: ⎆ Migration to pull-streams (from Node.js Streams) 

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs#403]
As noted in #362 I did the due diligence of confirming that using `pull-streams` all the way through solves our issues with secio. The result of this can be seen in https://github.com/libp2p/js-libp2p-swarm/pull/67. (**Warning** lots of module linking required to get this running)

The next step is to move from the prototype into a fully tested version for all modules. 
Below is a list of the modules that will need work.

### ipfs

- [ ] [`js-ipfs`](//github.com/ipfs/js-ipfs) - PR https://github.com/ipfs/js-ipfs/pull/440
- [x] [`interface-ipfs-core`](//github.com/ipfs/interface-ipfs-core) - PR https://github.com/ipfs/interface-ipfs-core/pull/70
- [x] [`js-ipfs-api`](//github.com/ipfs/js-ipfs-api) - delayed - Issue https://github.com/ipfs/js-ipfs-api/issues/367
- [x] [`js-ipfs-unixfs-engine`](//github.com/ipfs/js-ipfs-unixfs-engine) - PR https://github.com/ipfs/js-ipfs-unixfs-engine/pull/64
- [x] [`js-libp2p-ipfs`](//github.com/ipfs/js-libp2p-ipfs) (Only testing) - PR https://github.com/ipfs/js-libp2p-ipfs/pull/17
- [x] [`js-libp2p-ipfs-browser`](//github.com/ipfs/js-libp2p-ipfs-browser) (Only testing) - PR https://github.com/ipfs/js-libp2p-ipfs-browser/pull/84
- [x] [`js-ipfs-merkle-dag`](//github.com/ipfs/js-ipfs-merkle-dag) - PR https://github.com/ipfs/js-ipfs-merkle-dag/pull/44
- [x] [`js-ipfs-block-service`](//github.com/ipfs/js-ipfs-block-service) - PR https://github.com/ipfs/js-ipfs-block-service/pull/23
- [x] [`js-ipfs-ipld`](https://github.com/ipfs/js-ipfs-ipld) - PR https://github.com/ipfs/js-ipfs-ipld/pull/54
- [x] [`js-ipfs-repo`](//github.com/ipfs/js-ipfs-repo)  - PR https://github.com/ipfs/js-ipfs-repo/pull/76
- [x] **New** `interface-pull-blob-store` (replaces `abstract-blob-store`) https://github.com/ipfs/interface-pull-blob-store
- [x] **New** `idb-pull-blob-store` https://github.com/ipfs/js-idb-pull-blob-store
- [x] **New** `fs-pull-blob-store` https://github.com/ipfs/js-fs-pull-blob-store
- [x] [`js-ipfs-bitswap`](//github.com/ipfs/js-ipfs-bitswap) - PR https://github.com/ipfs/js-ipfs-bitswap/pull/25
- [x] [`js-multistream`](//github.com/multiformats/js-multistream) - PR https://github.com/multiformats/js-multistream/pull/19

### libp2p

- [x] [`interface-connection`](//github.com/libp2p/interface-connection) - PR https://github.com/libp2p/interface-connection/pull/10
- [x] [`js-libp2p-identify`](//github.com/libp2p/js-libp2p-identify) - PR https://github.com/libp2p/js-libp2p-identify/pull/2
- [x] [`js-libp2p-secio`](//github.com/libp2p/js-libp2p-secio) - PR https://github.com/libp2p/js-libp2p-secio/pull/8
- [x] [`js-libp2p-spdy`](//github.com/libp2p/js-libp2p-spdy) - PR https://github.com/libp2p/js-libp2p-spdy/pull/16
- [x] [`js-libp2p-websockets`](//github.com/libp2p/js-libp2p-websockets) - PR https://github.com/libp2p/js-libp2p-websockets/pull/18
- [x] [`js-libp2p-tcp`](//github.com/libp2p/js-libp2p-tcp) - PR https://github.com/libp2p/js-libp2p-tcp/pull/20
- [x] [`js-libp2p-webrtc-star`](//github.com/libp2p/js-libp2p-webrtc-star) PR https://github.com/libp2p/js-libp2p-webrtc-star/pull/12
- [x] [`js-libp2p-ping`](//github.com/libp2p/js-libp2p-ping) - PR https://github.com/libp2p/js-libp2p-ping/pull/11
- [x] [`js-libp2p-swarm`](//github.com/libp2p/js-libp2p-swarm) - PR https://github.com/libp2p/js-libp2p-swarm/pull/67
- [x] [`interface-stream-muxer`](//github.com/libp2p/interface-stream-muxer) - PR https://github.com/libp2p/interface-stream-muxer/pull/7
- [x] [`interface-transport`](//github.com/libp2p/interface-transport) - PR https://github.com/libp2p/interface-transport#8

### Documentation

- [x] Add a note about pull-streams to every readme
- [ ] Create a FAQ document collecting all important information on how to use pull-streams, how to convert them, why we use them etc.

**Comment by diasdavid** [comment]
Thank you for captaining this @dignifiedquire :) :) Let's make sure not to forget documentation :)

**Comment by dignifiedquire** [comment]
Draft for the readme note.

> This module uses [pull-streams](https://pull-stream.github.io/) for all stream based interfaces. You can find details of why we use them in this [document](). If you need to convert them to node-streams, you can do so easily with [pull-stream-to-stream](https://github.com/pull-stream/pull-stream-to-stream) like this:
```js
const toStream = require('pull-stream-to-stream')
const pullStream = getPullStream()
const myNodeStream = toStream(pullStream)
```

**Comment by jbenet** [comment]
before doing the work of chaning every module, i _highly_ recommend you pick a small set and work with them-- see how they go. You wont understand how an abstraction fits a project until you play with it for a while. and def better to find that out with a small set than after changing everything.

**Comment by dignifiedquire** [comment]
@jbenet we already did that as outlined at the beginning of this issue. I ported the minimal needed set to get secio in swarm working and see how things are working out, and they worked out great. Afterwards I talked with @diasdavid and we decided to move forward. The result of this is this endeveaour of moving all things into high quality ports.

**Comment by RichardLitt** [comment]
Sub. Let me know if I can help with READMEs.

**Comment by dignifiedquire** [comment]
Thanks @RichardLitt :heart: will ping you as soon as I have a consistent message ready.

**Comment by diasdavid** [comment]
Missing from the list:

- [ ] [js-multistream](https://github.com/libp2p/js-libp2p-spdy/pull/16)

**Comment by dignifiedquire** [comment]
> IPFS member
> diasdavid commented 31 minutes ago • edited
> Missing from the list:
> 
>  js-multistream

added

**Comment by diasdavid** [comment]
One more: https://github.com/libp2p/interface-transport/pull/8

**Comment by diasdavid** [comment]
## Status Update - The enchanted adventure of the missing backpressure mechanism.

The migration to pull-streams is almost complete, we currently have PR's across every single module that required to be updated in order for the migration to be complete. These PR include the code, documentation is still lacking.

There is one major blocker though, although we've been sucessful porting almost every single module to pull-streams, our stream-muxing stress tests are failing (fortunately we had them before this endeavour). We are still investigating the issue, having ruled out a bunch of the possible causes, we now have a strong conviction that the backpressure mechanism is failing when we convert back and forth pull and Node.js streams.

Me and @dignifiedquire have been spending a considerable amount of time debugging, if you would like to help, I've created 3 PR with different experiments and have added a way to test it, so you can observe the failures by yourself. All of these are documented:

- https://github.com/libp2p/js-libp2p-spdy/pull/19
- https://github.com/libp2p/js-libp2p-spdy/pull/20
- https://github.com/libp2p/js-libp2p-spdy/pull/21

|                                                      | tests | stress tests             | mega stress tests |
|------------------------------------------------------|-------|--------------------------|-------------------|
| Mode 0 (Current implementation, just Node.js Streams | ✔️     | ✔️                        | ✔️                 |
| Mode A                                               | ✔️     | 𝙓 (passes if throttled) | 𝙓 (and OOM)      |
| Mode B (Using Node.js Streams for transport)         | ✔️     | ✔️                        | OOM               |
| Mode C (Mimics real use)                             | ✔️     | 𝙓 (passes if throttled) | 𝙓 (and OOM)      |


In addition to the fact that (apparently), backpressure stops working properly when too much wrapping happens, we also see the process running Out Of Memory when tested exhaustively. This can be because the backpressure mechanism doesn't work as it should (keeping a lot of memory floating around) or simply because pull-streams have a high memory fingerprint, making the memory run out just because of having too many instances (less probable).

**Comment by dignifiedquire** [comment]
I finally had a breakthrough just now! I figured out why the pausing happens. The reason for it is that at some point the pull-stream side actually has too much data, and says "hey slow down" to the spdy-transport stream (the `framer` to be exact). This is happens via the `.write` call returning `false` (https://github.com/pull-stream/pull-stream-to-stream/blob/master/index.js#L36). 

After this everything comes to a halt quickly due to the fact that the `framer` is never resumed. 

The only somewhat viable solution I found so far was to add add 

```js
if (this.isPaused()) {
  this.resume()
}
```

to the `read` call in in the (`Scheduler.prototype._read`](https://github.com/indutny/spdy-transport/blob/master/lib/spdy-transport/protocol/base/scheduler.js#L91) which is the base class of the `framer`. The explanation as to why this makes sense, is that the `framer` is piped to the underlying transport. In the case the underlying transport exerts backpressure onto the `framer` it calls `.pause`. When it is ready to continue writing it will call `.read`, triggering the `._read` method on the source, i.e. this is the sign that the socket is ready to receive more data and as such the data flow can be resumed.

I am not certain in any way that this is the correct fix, so I'm very happy to receive more input here. One important step I have not done yet is to create a test case using only node streams to recreate this problem with backpressure on the underlying socket with spdy-transport.

**Comment by dignifiedquire** [comment]
I've created the above mentioned test and fix here: https://github.com/dignifiedquire/spdy-transport/commit/0e9c8475c2124577290b286ede9b822cb988bc30

**Comment by diasdavid** [comment]
@dignifiedquire where are the PR's for:

```
- [ ] js-libp2p-ipfs (Only testing)
- [ ]  js-libp2p-ipfs-browser (Only testing)
```

**Comment by diasdavid** [comment]
@dignifiedquire are there PR for the ipld-service?

**Comment by dignifiedquire** [comment]
@diasdavid no there is not, I would suggest changing that when we actually integrate it.

**Comment by diasdavid** [comment]
@dignifiedquire we've been directing some groups to check it out, we should make sure it continues to work

**Comment by dignifiedquire** [comment]
> we've been directing some groups to check it out

We did? Sure if people are actually using it we can update it now. I did not expect that

**Comment by diasdavid** [comment]
@dignifiedquire yep :)

I've made my CR to all the remaining repos, once all of those points are taken care (very little stuff), I'll do the merge and release \o/ :D

**Comment by diasdavid** [comment]
Woooo! All the Pull Streams are in :D
