### ISSUE TITLE
ipfs-repo level.js throws fallback error using create function at ipfs-core

### ISSUE THREAD

**Issue by ddevkim** [ipfs/js-ipfs#4039]
- **Version**: ipfs version 0.11.0

- **Platform**: macOS

- **Subsystem**: ipfs-core

#### Description:
in nodejs project (esm), I did as followings, (*(node version 16.3.1)
1. npm install ipfs-core  (*npm version 8.3.1)
2. import * as IPFS from "ipfs-core"
3. execute below code
4. const ipfs = await IPFS.create();
5. Here, I got error in console as below,
6. /node_modules/ipfs-repo/esm/src/utils/level.js:27
    throw new NotFountError();

in repo, level.js,
function getWithFallback throws error due to findLevelJs(store)  returns undefined.

There are no dependencies other than "ipfs-core", "ipfs-http-client", and "multiformats"

don't know what I was doing wrong. is there something I mixed up?

**Comment by amandesai01** [comment]
Can you also include `stdout` and `stderr` logs? Just to check exactly where the error originated (on which line).

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out! There are some examples in ipfs-examples/helia-examples using levelDatastore IIRC.
