### ISSUE TITLE
how do i know the % of file uploaded

### ISSUE THREAD

**Issue by atordvairn** [ipfs/js-ipfs#4084]
i am using js-ipfs http client npm package in a svelte application.
any way i can know jow much file is uploaded?
like, getting access to the `content-length` header

**Comment by achingbrain** [comment]
You can pass a `process` callback to [ipfs.add](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#options) - this will tell you how many bytes of a file have been processed.

You can use that to calculate out the total % if you figure out the size of the file you are adding before hand.

It's not possible to tell you the total % of the file that's been uploaded because the HTTP API does not wait for the file to be uploaded before it starts processing it.

**Comment by BigLep** [comment]
Closing for now since an answer was provided.
