### ISSUE TITLE
hey its a little confusing that the docs for get: say "store" - I think they are wrong?

### ISSUE THREAD

**Issue by gvelez17** [ipfs/js-ipfs#4136]
At https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core-types/src/dag/index.ts#L52

it says "Store an IPLD format node". and the example is "const cid = await ipfs.dag.put(obj, { storeCodec: 'dag-cbor', hashAlg: 'sha2-512' })"

I suppose the options are the same for get but when you are starting it is a little confusing - is this right?

**Comment by achingbrain** [comment]
I'm not sure I understand your question.

`storeCodec` is how the passed object will be encoded in the block that is ultimately added to your local node's repo.  This is different to `inputCodec` which can be used to interpret the passed object - see the `ipfs.dag.put` docs - https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/DAG.md#options-1

The options for `ipfs.dag.get` are different, there's no `storeCodec`/`inputCodec` because you are reading a block from the repo and the codec is either held in the CID (for v1 CIDs) or implicit dag-pb (for v0 CIDs).

If you think the comment can be improved, please open a PR!
