### ISSUE TITLE
Browser hangup during create method

### ISSUE THREAD

**Issue by metrocoding** [ipfs/js-ipfs#4171]
Hi, my browser is freezing till create promise is resolved in then.
only firefox, its ok on Safari and Chrome

```

<script src="https://cdn.jsdelivr.net/npm/ipfs-core@0.15.4/dist/index.min.js" integrity="sha256-BOLUCfwJIrl77f7h7q0mPaoJsOOrc+eE/i+XqTQSIJM=" crossorigin="anonymous"></script>

<script>
let ipfsNode = null;
const Ipfs = window.IpfsCore;
document.addEventListener("DOMContentLoaded", async () => {
    Ipfs.create().then(n => {
    // about 26000ms
        ipfsNode = n;
    });
});

  const  saveMetaData = async (metaData) => {
        try {
            //const ipfsNode = await Ipfs.create();
            const result = await ipfsNode.add(JSON.stringify(metaData));
            return result.path;
        } catch (e) {
            console.error("Error saving metadata to IPFS", e);
            return null;
        }
    }

</script>
```

- **Version**:
ipfs-core@0.15.4

- **Platform**:
macOS 12.5
browser firefox 102.0.1

#### Severity:
Medium

**Comment by legalizemath** [comment]
unless I'm missing something

`const  saveMetaData: async (metaData) => {` should probably be `const  saveMetaData = async (metaData) => {`

**Comment by metrocoding** [comment]
> unless I'm missing something
> 
> `const saveMetaData: async (metaData) => {` should probably be `const saveMetaData = async (metaData) => {`

I just made mistake in here by : instead of =
But it's fine in my real code the problem is with creat method only in firefox

**Comment by SgtPooki** [comment]
js-ipfs is being deprecated in favor of [Helia](https://github.com/ipfs/helia). You can https://github.com/ipfs/js-ipfs/issues/4336 and [read the migration guide](https://github.com/ipfs/helia/wiki/%F0%9F%9A%9B-Migrating-from-js-IPFS).

Please feel to reopen with any comments by 2023-06-02. We will do a final pass on reopened issues afterward (see https://github.com/ipfs/js-ipfs/issues/4336).

This issue is most likely resolved in Helia, please try it out!
