### ISSUE TITLE
Getting these errors on console after uploading data to IPFS

### ISSUE THREAD

**Issue by SyedImam1998** [ipfs/js-ipfs#4319]
- **Version**: "ipfs-core": "^0.18.0"

- **Platform**: Web

- **Subsystem**:

#### Description:
I am building my website using React Js (Vite) I have successfully uploaded my files to IPFS but after uploading when I check the console I can see these errors.

![image](https://user-images.githubusercontent.com/52135949/218948286-d6f9c21c-25dd-460b-948a-4e73afd8d023.png)

![image](https://user-images.githubusercontent.com/52135949/218948294-a1e35611-5234-47bd-abee-2efe20b9abd9.png)

**Comment by SgtPooki** [comment]
Hello @SyedImam1998,

Thank you for submitting this issue. Unfortunately, it seems like it's a problem that falls outside the scope of js-ipfs and IPFS. We appreciate your engagement and interest in our projects.

It seems like your having a problem with querying google and cloudflare DNS, not js-ipfs nor IPFS. The link https://dns.google/resolve?name=_dnsaddr.bootstrap.libp2p.io&type=TXT seems to work fine for me.

However, we would like to inform you that since we are in the process of deprecating js-ipfs, we will be focusing our efforts on our new library, helia. Therefore, we kindly request you to consider using helia for your future development needs. There are examples at https://github.com/ipfs-examples/helia-examples and our guide for migrating to helia from js-ipfs can be found at https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS.

While we understand that your current issue may not be directly related to js-ipfs, we encourage you to explore helia as it offers improved features and support that may address your use case more effectively. Please refer to https://github.com/ipfs/helia for further information and guidance.

We apologize for any inconvenience this may cause, but we believe that helia will provide you with a better experience and a more robust solution moving forward.

Thank you for your understanding and cooperation. We look forward to your continued support as we transition from js-ipfs to helia.

Best regards,
@ipfs/helia-dev
