### ISSUE TITLE
ipfs.add(stream) 504 gateway timeout

### ISSUE THREAD

**Issue by SourceBoy** [ipfs/js-ipfs#4347]
- **Version**: 0.18.0
```
{
  version: '0.18.0',
  commit: '',
  repo: '12',
  'ipfs-core': '0.18.0',
  'interface-ipfs-core': '^0.158.0'
}
```

- **Platform**: amd64 (docker node:18-slim)

- **Subsystem**: ipfs-core

#### Description:

`ipfs.add(<stream>)` receives a cid but gets a 504 during content retrieval.
Doc ref: https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#filecontent

#### Steps to reproduce the error:
```javascript
import * as IPFS from 'ipfs-core';

// const stream = Neither WHATWG ReadableStream nor Node stream.Readable works

(async () => {
  const ipfs = await IPFS.create();
  const result = await ipfs.add(stream);
  console.log(result);
})();
```

**Comment by SgtPooki** [comment]
Hi there! 

Thank you for reaching out to us. 

It seems like the core issue you're running into is that you are getting a 504 "gateway timeout" when attempting to retrieve your content, but you haven't really specified how you're trying to retrieve your content. This could be due to not "publishing" the data you created/added on ipfs, or downloading too much content from the gateway you're using, etc.

In regards to your code and methods, we recommend that you use @helia/unixfs and helia instead of js-ipfs. Our team has decided to [deprecate js-ipfs](https://github.com/ipfs/js-ipfs/issues/4336) due to certain issues that have come up. We believe that @helia/unixfs and helia are the best alternatives for your needs. 

You can check out the helia migration guide at https://github.com/ipfs/helia/wiki/Migrating-from-js-IPFS

Please let us know if you have any other questions or concerns.

**Comment by SourceBoy** [comment]
Content was retrieved from `https://ipfs.io/ipfs/<cid>` as shown from the [doc section](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#filecontent).

The `.add()` call did return a cid back.

Does @helia/unixfs support adding a WHATWG ReadableStream or Node stream.Readable? Our use case is to take a http stream upload and then stream-upload the file to IPFS without buffering the file in memory or storing the file on file system.

Thanks.

**Comment by SgtPooki** [comment]
@SourceBoy it looks like unix-fs supports adding content via byteStreams only (you can see the tests at https://github.com/ipfs/helia-unixfs/blob/main/packages/unixfs/test/add.spec.ts), so if you were to pass a stream in, I think you'd need to first pipe that stream to something that would return the bytes. 

https://www.npmjs.com/package/ipfs-unixfs-importer is the package that @helia/unixfs is using with the `addAll` and `addBytes` methods. They accept an `ImportCandidateStream` and `ByteStream` respectively. Check out https://github.com/ipfs/js-ipfs-unixfs/tree/master/packages/ipfs-unixfs-importer#api for details on what's going on behind the scenes.

**Comment by SourceBoy** [comment]
@SgtPooki Thank you

**Comment by SgtPooki** [comment]
No problem! Please let us know with a an issue on the helia/unixfs repo if helia/unixfs doesn't work for your usecase and we’ll work to help you out there :)
