### ISSUE TITLE
browser compatibility

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs#586]
https://github.com/ipfs/js-ipfs/pull/485#issuecomment-260065517

**Comment by VictorBjelkholm** [comment]
Issue is this:

```
CI is finally green, browsers are not perfect atm, most are failing due to one or the other issue

Firefox fails with this

Firefox 49.0.0 (Linux 0.0.0) ERROR
  SyntaxError: missing = in const declaration
  at webpack:///~/cbor/lib/encoder.js:383:0 <- test/browser.js:41233

though this code runs fine in Chrome.
```

Which I tracked down to being about either `const` being used inside `for()` or using `const` without a initialize value. So, in the end, turns out the issue is in `cbor` library we use, specifically here: https://github.com/hildjj/node-cbor/blob/master/lib/encoder.js#L383

I've submitted a patch here:  https://github.com/hildjj/node-cbor/pull/39

**Comment by hildjj** [comment]
Upgrade to version 3.0.0, includes this and canonicalization.

**Comment by diasdavid** [comment]
Thank you @hildjj !!! 🎉


@VictorBjelkholm I've updated https://github.com/ipld/js-ipld-dag-cbor/commit/05170d74f1c82bb54d177103280d91a522841b78 this should be good now :) rerunning CI
