### ISSUE TITLE
Run interface-ipfs-core testst in the browser

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs#588]
We need to run those tests with js-ipfs-api against a js-ipfs intance from the browser to ensure things work as expected

**Comment by diasdavid** [comment]
@dignifiedquire there is no js-ipfs-api to a js-ipfs instance in the browser, since js-ipfs in the browser doesn't have http

if you mean running interface-ipfs-core tests against js-ipfs core, in nodejs and browser then it is what is happening, see:

- https://github.com/ipfs/js-ipfs/tree/master/test/core/both

**Comment by diasdavid** [comment]
@dignifiedquire could you follow up in this one? Still not sure if there is work to be done here

**Comment by dignifiedquire** [comment]
Hmm I think we can close this for now then.
