### ISSUE TITLE
Run tests inside electron Node.js and Browser process as well

### ISSUE THREAD

**Issue by harshjv** [ipfs/js-ipfs#697]
When running `js-ipfs` daemon with `Electron` via JS API with `js-ipfs daemon` running in background, `js-ipfs` in Electron process throws this error every time it encounters a peer (other js-ipfs node).

### Electron node

    "Addresses": {
      API: "/ip4/127.0.0.1/tcp/5003",
      Swarm: [
        "/ip4/0.0.0.0/tcp/4003",
        "/libp2p-webrtc-star/ip4/188.166.203.82/tcp/20000/ws/ipfs/<PEER-ID>"
      ],
      Gateway: "/ip4/0.0.0.0/tcp/8083"
    }

### `js-ipfs` node

    "Addresses": {
      API: "/ip4/127.0.0.1/tcp/5002",
      Swarm: [
        "/ip4/0.0.0.0/tcp/4002",
        "/libp2p-webrtc-star/ip4/188.166.203.82/tcp/20000/ws/ipfs/<PEER-ID>"
      ],
      Gateway: "/ip4/0.0.0.0/tcp/8082"
    }

## Error in `js-ipfs` node in electron process

    Uncaught Exception:
    TypeError: Cannot read property 'getRandomValues' of undefined
        at Object.exports.randomBytes (/Users/Project/app/node_modules/libp2p-secio/src/support.js:80:38)
        at Object.exports.createProposal (/Users/Project/app/node_modules/libp2p-secio/src/handshake/crypto.js:21:19)
        at propose (/Users/Project/app/node_modules/libp2p-secio/src/handshake/propose.js:18:31)
        at series (/Users/Project/app/node_modules/libp2p-secio/src/handshake/index.js:13:13)
        at /Users/Project/app/node_modules/async/internal/parallel.js:27:9
        at replenish (/Users/Project/app/node_modules/async/internal/eachOfLimit.js:64:17)
        at /Users/Project/app/node_modules/async/internal/eachOfLimit.js:68:9
        at eachOfLimit (/Users/Project/app/node_modules/async/eachOfLimit.js:37:36)
        at /Users/Project/app/node_modules/async/internal/doLimit.js:9:16
        at _parallel (/Users/Project/app/node_modules/async/internal/parallel.js:26:5)
        at series (/Users/Project/app/node_modules/async/series.js:83:26)
        at handshake (/Users/Project/app/node_modules/libp2p-secio/src/handshake/index.js:12:3)
        at encrypt (/Users/Project/app/node_modules/libp2p-secio/src/index.js:36:7)
        at Object.swarm.handle [as handlerFunc] (/Users/Project/app/node_modules/libp2p-swarm/src/connection.js:87:24)
        at matcher (/Users/Project/app/node_modules/multistream-select/src/listener/select-handler.js:40:28)
        at some (/Users/Project/app/node_modules/multistream-select/src/listener/select-handler.js:71:7)

## Platform
Electron v1.4.13

**Comment by harshjv** [comment]
This issue is more complex than I thought. The problem is with dependencies using OpenSSL but Chromium is using some fork of OpenSSL.

I found some related issues with dependencies worth tracking for this issue:

https://github.com/libp2p/js-libp2p-crypto/issues/38
https://github.com/PeculiarVentures/node-webcrypto-ossl/issues/77
https://github.com/electron/electron/issues/1410#issuecomment-152407010

:/

**Comment by diasdavid** [comment]
Oh, this is super annoying :( So in essence, **`js-ipfs` in the Node.js process of electron won't work because of incompatible crypto binding, it will work in the Browser process only since it uses WebCrypto directly.**

I see that the electron team tagged it as `wont fix`, offering the alternative that modules using it will have to bundle the native crypto library themselves. This actually doesn't go that far from that we had discussed since we wanted to remove that ugly install experience anyway. The hard problem is really with shipping bundling 'crypto binaries' (what could go wrong there).

[node-webcrypto-ossl is actually an optional dependency](https://github.com/libp2p/js-libp2p-crypto/blob/master/package.json#L54-L56) at the moment and there is a fallback to straight JavaScript, making it slower, but functional. I would argue that is best to remove node-webcrypto-ossl entirely for the moment until there is a good solid solution, removing the frustration for both electron users and windows users. @dignifiedquire am I missing anything that might go against this proposal?

Thank you for the report and debugging @harshjv

**Comment by haadcode** [comment]
> I would argue that is best to remove node-webcrypto-ossl entirely for the moment until there is a good solid solution, removing the frustration for both electron users and windows users.

As much I would not like to downgrade the crypto perf, I would agree with @diasdavid's proposal.

**Comment by diasdavid** [comment]
Thank you @haadcode. Anyone against?

**Comment by dignifiedquire** [comment]
Yes I am. As mentioned before we can detect electron and fallback to pure js in the main process, without needing to drop the perf improvements in regular node.js scenarios.

**Comment by diasdavid** [comment]
Let's try that :)

**Comment by diasdavid** [comment]
@dignifiedquire also, can we get aegir to also run the tests inside electron for us? Same way as in Node.js, Browser and WebWorker. Ideally, we would run tests inside the browser process and node.js process.

**Comment by diasdavid** [comment]
Created https://github.com/ipfs/aegir/issues/157 in aegir to track this. #843 is the main issue to track supporting electron. Closing this one :)
