### ISSUE TITLE
files.add() returns folders hashes as well

### ISSUE THREAD

**Issue by negamaxi** [ipfs/js-ipfs#731]
Trying to understand meaning of `path` filed in `file` object. It seems `files.add()` builds hashes from  streams/buffers, but when I'm put relative path string into `path` field it returns additional hases for folders too.

```javascript
// files - array with relative path strings
const promises = files.map(async (filePath) => {
  //const fileName = path.basename(filePath)
  try {
    const stream = await fs.createReadStream(filePath)
    const file = {
        path: filePath // fileName works as well,
        content: stream
    }
    return file
  } catch(e) {
    console.log(e)
  }
})
const files = await Promise.all(promises)
console.log(files) 
/*
 [ { path: './testFolder/3504.jpg',
    content: 
     ReadStream ,
  { path: './testFolder/a49b7cd5_image.jpeg',
    content: ReadStream ]
*/
const result = await node.files.add(files)
console.log(result)
/*
[ { path: './testFolder/a49b7cd5_image.jpeg',
    hash: 'QmPgCHfxHNyiPAVSHdjrBUKgP9u7PXL6PhDyzb3yTDhpSv',
    size: 556563 },
  { path: './testFolder/3504.jpg',
    hash: 'QmPL6RAMJP3svDub5CFqkgNvBSwtuXHBNWY3htHB7uoNoS',
    size: 32235 },
  { path: './testFolder',
    hash: 'QmWb4SzsNhmP2YdvcczCZW2aHXLURfgVvaK9rDCwka3Us9',
    size: 588917 },
  { path: '.',
    hash: 'QmU9b7SiNM4M6doZJFK7PsvNkurJ5aj5BRWJkDbBu5D26u',
    size: 588975 } ]
*/
```
If I use `fileName` instead of `filePath` it returns only two hashes for each file. Which kind of path should I use then, relative or filename? Is there any use cases? Thanks.

**Comment by diasdavid** [comment]
Hi @negamaxi, just wondering if you found https://github.com/ipfs/interface-ipfs-core/tree/master/API/files#add and if that was useful to you?

`files.add` will take an array of files described in `{ path:, content }`, where path is the path from the root to the where the content lives, think it as a DAG, it has always a starting point and everything expands from there.

When you add a `.`, it is assuming that is one of the levels of that directory and so creates a dirNode with that name. This makes an interesting question, should we catch this cases and report them to the user as errors, since `.` is not a valid name for a directory?

**Comment by negamaxi** [comment]
Hi @diasdavid, thanks for your response. Yes, I've read Api docs for `files.add()` before using it, but I'm still missing the point of `path` field, as nothing stops me from passing such objects `{ path: "my-file.txt", content: Stream }` or even `{ path: "", content: Stream }`. In the last case `path` field will be containing a file hash, and I haven't seen explanation for such behavior in docs. 

So I'm just trying to understand the purpose of this `path` field and when I should put there absolute/relative path or just filename or even empty string, as all of this allowed.

**Comment by diasdavid** [comment]
The `path` field purpose is to that you can construct your directory tree. Adding a file with no path is parallel to an `ipfs add fileName`, where you add the file, but you loose the name when you get back the hash, while adding a file with a path is parallel to `ipfs add fileName -w`, which wraps the file in a dir node so that you preserve the filename.

**Comment by diasdavid** [comment]
Did I answer your question @negamaxi ? Let me know if not. Closing this now.
