### ISSUE TITLE
Example: use in the browser

### ISSUE THREAD

**Issue by jbenet** [ipfs/js-ipfs#845]
browser examples do not show how to connect to network... no idea how to connect an in-browser js-ipfs to the rest of the network

**Comment by diasdavid** [comment]
Did you get the chance to look at the [`transfer-files`](https://github.com/ipfs/js-ipfs/tree/master/examples/transfer-files) example? You should see this:

![image](https://cloud.githubusercontent.com/assets/1211152/25800674/95429504-33ea-11e7-890f-a781881e60cb.png)

**Comment by grncdr** [comment]
I would support @jbenet's concern here, I'll explain the step I took:

1. I tried to start with `ipfs.files.cat` and a known multihash, but this will just hang indefinitely AFAICT.
2. I then looked at the `browser-script-tag` example, which worked, but only with data added to the same local repo.
3. I eventually looked at open issues, and this one was (thankfully) near the top of the list.
4. I then looked at the `transfer-files` example to find this note:

   > js-ipfs currently doesn't support DHT peer discovery, the peer from which you are fetching data should be within the reach (local or in public IP) of the browser node.

If this is (still) true, it should be front and center in the project README wherever usage in-browser is mentioned.

**Comment by grncdr** [comment]
In case my previous comment sounded negative... it's *awesome* to see that this does in fact work! 👍

**Comment by diasdavid** [comment]
All valid points, thanks for the feedback @grncdr :) 

At the current moment, you can fetch any data that is available to the Bootstraper nodes/gateways due to the lack of DHT as you learned. That said though, we are really onto the [DHT](https://github.com/ipfs/js-ipfs/pull/856) and [Relay](https://github.com/ipfs/js-ipfs/pull/830), the last to pieces to make this just work seamlessly for everyone.

I've updated the README to contain this information https://github.com/ipfs/js-ipfs#project-status

**Comment by diasdavid** [comment]
Moar examples, now with video (thanks to @pgte):

- https://www.youtube.com/watch?v=Nv_Teb--1zg&t=235s
- https://www.youtube.com/watch?v=-kdx8rJd8rQ&t=64s

**Comment by diasdavid** [comment]
Please see all the other examples at https://github.com/ipfs/js-ipfs/tree/master/examples. Closing this issue for now :)
