### ISSUE TITLE
Hashes created on iPad not resolvable through ipfs.io gateway

### ISSUE THREAD

**Issue by edsilv** [ipfs/js-ipfs#872]
I'm seeing an issue on my iPad where hashes created with js-ipfs are not resolvable through the ipfs.io gateway.

Here's a test page: https://edsilv.github.io/ipfs-tests/ipad.html

https://github.com/edsilv/ipfs-tests/blob/gh-pages/ipad.html

I'm creating a cache-busted json object, adding it, then generating a link to view on the gateway.

Here's the user agent string:

```
Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1
```

It seems to have the same problem in Chrome for iPad too.

**Comment by diasdavid** [comment]
Hi @edsilv, it seems that your demo doesn't work on Safari Desktop, you might have missed this by testing it on a Windows environment.

Checking the JS console on desktop, I noticed that the daemon never gets online.

![image](https://cloud.githubusercontent.com/assets/1211152/26531252/53a9853c-43dd-11e7-8eb6-2d9326360ba2.png)

This might be because it is trying to use WebRTC and it fails to create that listener. It should print an error though, are you swallowing the errors with some Promise wrap? 

To disable WebRTC, on your node creation, do:

```
const node = new IPFS({
  config: {
    Addresses: {
      Swarm: []
    }
  }
})
```

https://github.com/ipfs/js-ipfs#advanced-options-when-creating-an-ipfs-node

**Comment by diasdavid** [comment]
Ok, I've been doing more tests on this, I knew there was something more why Safari wasn't fully supported, but I was missing to remember, now I know.

See:

![image](https://cloud.githubusercontent.com/assets/1211152/26531339/1d3af8b2-43df-11e7-8a2f-c9e0b99d35c4.png)

The WebCrypto spec is not fully implemented in Safari yet: https://github.com/libp2p/js-libp2p-crypto/issues/18

**Comment by diasdavid** [comment]
@edsilv now that you have it going on your Android phone I look forward to see the demo! :D Closing this issue :)
