### ISSUE TITLE
Daemon dies with segfaults and Bus error: 10 (also unequal MACs earlier)

### ISSUE THREAD

**Issue by JohnAllen** [ipfs/js-ipfs#878]
I got the above errors when running `jsipfs add -r .` (add single file works).  Prior seemingly all `jsipfs` command responded with nothing or worked improperly.

I'll try to help if possible.

- MacOS: 10.12.4
-   "_id": "ipfs@0.24.1"
- Node v6.10.1
- npm 3.10.0

Let me know how I can help fix this!

The directory is somewhat large, MBs.  It's a large js repo.  I tried `.` and `cd ..; jsipfs add -r dirName` with same behavior.

**Comment by JohnAllen** [comment]
Ok a small dir of three empty .txt files works.  Is it possible to serve a large JS bundle?  Shouldn't I be able to do this from command line?  Appreciate the help.

**Comment by diasdavid** [comment]
Hi @JohnAllen, thanks for reporting this bug!

I believe I know what is the bug, it is not related with adding files but with using WebRTC. I've been noticing that the WRTC module is now more unstable (than ever) and since we added WebRTC as a default transport in Node.js (and browser), it is crashing the jsipfs daemon. 

I believe I will disable WebRTC as default in Node.js in the next version, although it makes me incredibly sad as I wanted the users to be able to use it out of the box. 

wrtc: https://www.npmjs.com/package/wrtc

**Comment by JohnAllen** [comment]
Thanks for the help solving this!  Can I ask what are the benefits of use WRTC over other alternatives? Are there not other real-time communications transports?  Just curious and want to learn more.

**Comment by JohnAllen** [comment]
I can report that this does prevent the daemon from crashing but it seems the files are not added to IPFS (but can confirm adding on smaller directories does work).  I will look for some more JS bundle app examples.  Perhaps we can build our app in a way that is more suitable to JS-IPFS

**Comment by diasdavid** [comment]
WRTC is the WebRTC implementation available for Node.js, we use multiple transports in IPFS to support it working in different environments (i.e desktop, browser, etc)

when you are adding large directories, does the process end or does it get stale? It might be the case that it is still adding, js-ipfs currently doesn't have progress bar support. If you would like to take a stab at it, see: https://github.com/ipfs/js-ipfs-unixfs-engine/issues/123

**Comment by JohnAllen** [comment]
Yeah actually started working on progress bar support earlier. So will take
a stab :)
