### ISSUE TITLE
Question about running `swarm.peers()` in setInterval 

### ISSUE THREAD

**Issue by JohnAllen** [ipfs/js-ipfs#970]
#### Description: 
@diasdavid: in this [comment](https://github.com/ipfs/js-ipfs/issues/800#issuecomment-288035837) you said: `Let's try one more thing, spawn several browser tabs with your code and instead of doing just once node.swarm.peers do it in a setInterval.` . How does this work?  Is it simply: running this function more than once tells the network to connect to more peers?`.  This seems to be the case because the more times it is run the more peers I have.  Wondering if there is more to it than that.

**Comment by diasdavid** [comment]
> oh these magic black boxes :) 🎩

[ipfs.swarm.peers](https://github.com/ipfs/interface-ipfs-core/tree/master/API/swarm#peers) lists the peers connected, connecting to a peer is not instance, it has to go through an intense handshake of `multistream -> secio -> multistream -> multiplex -> multistream`, which can take some seconds per peer. The reason why you see more and more is because your now is not only connecting to the bootstrapper nodes, it is also connecting to other nodes it discovers and so, over time, the peer list will increase.

**Comment by diasdavid** [comment]
@JohnAllen do you feel your question got answered?

**Comment by JohnAllen** [comment]
Yes, thanks, meant to close!
